### ISSUE TITLE
runtime error invalid memory address or nil pointer dereference when restart dockerd

### ISSUE THREAD

**Issue by starplanet** [docker/for-linux#107]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior

dockerd start successfully

### Actual behavior

dockered start failed, and output the following:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x1587305]

goroutine 2350 [running]:
github.com/docker/docker/daemon.(*Daemon).createSpec(0xc420256000, 0xc420257d40, 0x0, 0x0, 0xc420256000)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/oci_linux.go:778 +0x1235
github.com/docker/docker/daemon.(*Daemon).containerStart(0xc420256000, 0xc420257d40, 0x0, 0x0, 0x0, 0x0, 0xc421014000, 0x0, 0x0)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/start.go:144 +0x22a
github.com/docker/docker/daemon.(*Daemon).StateChanged.func1(0xc420d95ce0, 0xc420256000, 0xc420257d40, 0xc422cc6220, 0x4, 0x0, 0x0, 0x0, 0x0)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/monitor.go:72 +0x26d
created by github.com/docker/docker/daemon.(*Daemon).StateChanged
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/monitor.go:83 +0x6ba
```

### Steps to reproduce the behavior

/usr/bin/dockerd

**Output of `docker version`:**

```
lient:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:20:36 2017
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```

```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by thaJeztah** [comment]
Can you try updating to docker 17.06.2 ? The docker 17.06.1 and 17.06.2 patch releases fix various issues, including a panic (which may be what you're seeing here)

**Comment by starplanet** [comment]
OK, I will try.

**Comment by thaJeztah** [comment]
Closing because this went stale, but comment if you still ran into this after updating
