### ISSUE TITLE
Docker rootless fail randomly

### ISSUE THREAD

**Issue by hube12** [docker/for-linux#1089]
* [x] This is a bug report
* [ ] This is a feature request
* [X] I searched existing issues before opening this one

### Expected behavior
Docker rootless will fail randomly after some time.

### Actual behavior
Docker rootless service should not be killed

### Steps to reproduce the behavior
It happened randomly after 3 days, no container nor other action was made

**Output of `docker version`:**

```
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:42:53 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:49:35 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 19.03.12
 Storage Driver: vfs
 Logging Driver: json-file
 Cgroup Driver: none
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
  rootless
 Kernel Version: 4.19.0-10-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 1.948GiB
 Name: XXXXX
 ID: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 Docker Root Dir: /home/XXXXX/.local/share/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

Here the syslog:

```log
Aug 20 16:29:39 XXXXXXXX systemd[1]: session-60.scope: Succeeded.
Aug 20 16:59:20 XXXXXXXX systemd[1]: session-1.scope: Succeeded.
Aug 20 16:59:30 XXXXXXXX systemd[1]: Stopping User Manager for UID 1000...
Aug 20 16:59:31 XXXXXXXX systemd[480]: Stopped target Default.
Aug 20 16:59:31 XXXXXXXX dockerd-rootless.sh[7899]: time="2020-08-20T16:59:31.293570752+02:00" level=info msg="shim reaped" id=f30919aed4e11f310fe4fe358b55f3b7f4f3bb26e135a4dec8da67c36f30b683
Aug 20 16:59:31 XXXXXXXX dockerd-rootless.sh[7899]: time="2020-08-20T16:59:31.293697473+02:00" level=warning msg="cleaning up after killed shim" id=f30919aed4e11f310fe4fe358b55f3b7f4f3bb26e135a4dec8da67c36f30b683 namespace=moby
Aug 20 16:59:31 XXXXXXXX systemd[480]: Stopping Docker Application Container Engine (Rootless)...
Aug 20 16:59:31 XXXXXXXX dockerd-rootless.sh[7899]: panic: time="2020-08-20T16:59:31.234125550+02:00" level=info msg="Processing signal 'terminated'"
Aug 20 16:59:31 XXXXXXXX dockerd-rootless.sh[7899]: vif2tap: read: EOF
Aug 20 16:59:31 XXXXXXXX dockerd-rootless.sh[7899]: goroutine 10 [running]:
Aug 20 16:59:31 XXXXXXXX dockerd-rootless.sh[7899]: github.com/rootless-containers/rootlesskit/pkg/network/vpnkit.vif2tap(0x7f77fd2e81b8, 0xc00000ce00, 0xc00008c370)
Aug 20 16:59:31 XXXXXXXX dockerd-rootless.sh[7899]: #011/tmp/tmp.lkE4iJEEY1/src/github.com/rootless-containers/rootlesskit/pkg/network/vpnkit/vpnkit.go:207 +0xed
Aug 20 16:59:31 XXXXXXXX dockerd-rootless.sh[7899]: created by github.com/rootless-containers/rootlesskit/pkg/network/vpnkit.startVPNKitRoutines
Aug 20 16:59:31 XXXXXXXX dockerd-rootless.sh[7899]: #011/tmp/tmp.lkE4iJEEY1/src/github.com/rootless-containers/rootlesskit/pkg/network/vpnkit/vpnkit.go:186 +0x576
Aug 20 16:59:31 XXXXXXXX kernel: [184700.673441] br-5136c983d71a: port 2(veth5ace379) entered disabled state
Aug 20 16:59:31 XXXXXXXX kernel: [184700.673796] device veth5ace379 left promiscuous mode
Aug 20 16:59:31 XXXXXXXX kernel: [184700.673798] br-5136c983d71a: port 2(veth5ace379) entered disabled state
Aug 20 16:59:31 XXXXXXXX dockerd-rootless.sh[7899]: [rootlesskit:parent] error: child exited: exit status 2
Aug 20 16:59:31 XXXXXXXX systemd[480]: docker.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 20 16:59:31 XXXXXXXX kernel: [184700.701951] device vetha92d237 left promiscuous mode
Aug 20 16:59:31 XXXXXXXX kernel: [184700.701963] br-5136c983d71a: port 1(vetha92d237) entered disabled state
Aug 20 16:59:33 XXXXXXXX systemd[480]: docker.service: Failed with result 'exit-code'.
Aug 20 16:59:33 XXXXXXXX systemd[480]: Stopped Docker Application Container Engine (Rootless).
Aug 20 16:59:33 XXXXXXXX systemd[480]: Stopped target Basic System.
Aug 20 16:59:33 XXXXXXXX systemd[480]: Stopped target Timers.
Aug 20 16:59:33 XXXXXXXX systemd[480]: Stopped target Sockets.
Aug 20 16:59:33 XXXXXXXX systemd[480]: Stopped target Paths.
Aug 20 16:59:33 XXXXXXXX systemd[480]: Reached target Shutdown.
Aug 20 16:59:33 XXXXXXXX systemd[480]: systemd-exit.service: Succeeded.
Aug 20 16:59:33 XXXXXXXX systemd[480]: Started Exit the Session.
Aug 20 16:59:33 XXXXXXXX systemd[480]: Reached target Exit the Session.
Aug 20 16:59:33 XXXXXXXX systemd[1]: user@1000.service: Succeeded.
Aug 20 16:59:33 XXXXXXXX systemd[1]: Stopped User Manager for UID 1000.
Aug 20 16:59:33 XXXXXXXX systemd[1]: Stopping User Runtime Directory /run/user/1000...
Aug 20 16:59:33 XXXXXXXX systemd[1]: run-user-1000.mount: Succeeded.
Aug 20 16:59:33 XXXXXXXX systemd[1]: user-runtime-dir@1000.service: Succeeded.
Aug 20 16:59:33 XXXXXXXX systemd[1]: Stopped User Runtime Directory /run/user/1000.
Aug 20 16:59:33 XXXXXXXX systemd[1]: Removed slice User Slice of UID 1000.
```

**Comment by hube12** [comment]
My bad, I forgot to enable lingering, turns out my account was kept alive by a cron script which i remove thus making the account inactive.
This command should be emphatized:
``` sudo loginctl enable-linger $(whoami)```
