### ISSUE TITLE
Docker engine doesn't start while on VPN

### ISSUE THREAD

**Issue by endrsmar** [docker/for-linux#1190]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
Docker engine works regardless of VPN connection

### Actual behavior
Docker wont' start while I'm on VPN

### Steps to reproduce the behavior
- connect to VPN
- sudo service docker restart

**Output of `docker version`:**

```
Docker version 20.10.1, build 831ebea
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.0-docker)

Server:
 Containers: 4
  Running: 0
  Paused: 0
  Stopped: 4
 Images: 69
 Server Version: 20.10.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.8.0-38-generic
 Operating System: Ubuntu 20.10
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.52GiB
 Name: REDACTED
 ID: REDACTED
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio weight support
WARNING: No blkio weight_device support
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
Routes while on VPN:
```
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         0.0.0.0         0.0.0.0         U     50     0        0 ppp0
0.0.0.0         192.168.68.1    0.0.0.0         UG    600    0        0 wlp2s0
169.254.0.0     0.0.0.0         255.255.0.0     U     1000   0        0 wlp2s0
187.13.0.0      192.168.68.1    255.255.0.0     UG    600    0        0 ppp0
187.13.202.216  192.168.68.1    255.255.255.255 UGH   600    0        0 wlp2s0
192.168.68.0    0.0.0.0         255.255.255.0   U     600    0        0 wlp2s0
192.168.68.1    0.0.0.0         255.255.255.255 UH    600    0        0 wlp2s0
```
Journal output:
```
led 03 14:25:41 endrsmar dockerd[1203]: time="2021-01-03T14:25:41.112184376+01:00" level=info msg="Starting up"
led 03 14:25:41 endrsmar dockerd[1203]: time="2021-01-03T14:25:41.112926059+01:00" level=info msg="detected 127.0.0.53 nameserver, assuming systemd-resolved, so using resolv.conf: /run/systemd/resolve/resolv.co>
led 03 14:25:41 endrsmar dockerd[1203]: time="2021-01-03T14:25:41.140039384+01:00" level=info msg="parsed scheme: \"unix\"" module=grpc
led 03 14:25:41 endrsmar dockerd[1203]: time="2021-01-03T14:25:41.140058559+01:00" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
led 03 14:25:41 endrsmar dockerd[1203]: time="2021-01-03T14:25:41.140073953+01:00" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>>
led 03 14:25:41 endrsmar dockerd[1203]: time="2021-01-03T14:25:41.140087640+01:00" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
led 03 14:25:41 endrsmar dockerd[1203]: time="2021-01-03T14:25:41.143829614+01:00" level=info msg="parsed scheme: \"unix\"" module=grpc
led 03 14:25:41 endrsmar dockerd[1203]: time="2021-01-03T14:25:41.143845681+01:00" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
led 03 14:25:41 endrsmar dockerd[1203]: time="2021-01-03T14:25:41.143865646+01:00" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>>
led 03 14:25:41 endrsmar dockerd[1203]: time="2021-01-03T14:25:41.143882787+01:00" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
led 03 14:25:41 endrsmar dockerd[1203]: time="2021-01-03T14:25:41.167241063+01:00" level=info msg="[graphdriver] using prior storage driver: overlay2"
led 03 14:25:41 endrsmar dockerd[1203]: time="2021-01-03T14:25:41.178385506+01:00" level=warning msg="Your kernel does not support CPU realtime scheduler"
led 03 14:25:41 endrsmar dockerd[1203]: time="2021-01-03T14:25:41.178446392+01:00" level=warning msg="Your kernel does not support cgroup blkio weight"
led 03 14:25:41 endrsmar dockerd[1203]: time="2021-01-03T14:25:41.178468539+01:00" level=warning msg="Your kernel does not support cgroup blkio weight_device"
led 03 14:25:41 endrsmar dockerd[1203]: time="2021-01-03T14:25:41.178884247+01:00" level=info msg="Loading containers: start."
led 03 14:25:41 endrsmar dockerd[1203]: time="2021-01-03T14:25:41.518927812+01:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a>
led 03 14:25:41 endrsmar dockerd[1203]: time="2021-01-03T14:25:41.584981621+01:00" level=info msg="Loading containers: done."
led 03 14:25:41 endrsmar dockerd[1203]: time="2021-01-03T14:25:41.647391935+01:00" level=info msg="Docker daemon" commit=f001486 graphdriver(s)=overlay2 version=20.10.1
led 03 14:25:41 endrsmar dockerd[1203]: time="2021-01-03T14:25:41.648356311+01:00" level=info msg="Daemon has completed initialization"
led 03 14:25:41 endrsmar systemd[1]: Started Docker Application Container Engine.
led 03 14:25:41 endrsmar dockerd[1203]: time="2021-01-03T14:25:41.679721500+01:00" level=info msg="API listen on /run/docker.sock"
led 03 14:26:27 endrsmar dockerd[1203]: time="2021-01-03T14:26:27.843646255+01:00" level=info msg="ignoring event" container=170b3b469664f145ca395ececdb4fee13c950ecfa9dc297e4ff3cec49a2d2da7 module=libcontainerd>
led 03 14:30:39 endrsmar dockerd[1203]: time="2021-01-03T14:30:39.195910196+01:00" level=warning msg="Error getting v2 registry: Get https://docker.rohea.com/v2/: net/http: request canceled while waiting for co>
...skipping...
led 20 10:46:54 endrsmar dockerd[15500]: time="2021-01-20T10:46:54.238709722+01:00" level=warning msg="Your kernel does not support CPU realtime scheduler"
led 20 10:46:54 endrsmar dockerd[15500]: time="2021-01-20T10:46:54.238732887+01:00" level=warning msg="Your kernel does not support cgroup blkio weight"
led 20 10:46:54 endrsmar dockerd[15500]: time="2021-01-20T10:46:54.238737951+01:00" level=warning msg="Your kernel does not support cgroup blkio weight_device"
led 20 10:46:54 endrsmar dockerd[15500]: time="2021-01-20T10:46:54.238862491+01:00" level=info msg="Loading containers: start."
led 20 10:46:54 endrsmar dockerd[15500]: panic: runtime error: invalid memory address or nil pointer dereference
led 20 10:46:54 endrsmar dockerd[15500]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x55e2e6d7c5e2]
led 20 10:46:54 endrsmar dockerd[15500]: goroutine 1 [running]:
led 20 10:46:54 endrsmar dockerd[15500]: github.com/docker/docker/vendor/github.com/vishvananda/netlink.parseAddr(0xc0000e2d6c, 0x38, 0x38, 0x0, 0xc000e9488c, 0x4, 0x280, 0x0, 0x0, 0x0, ...)
led 20 10:46:54 endrsmar dockerd[15500]:         /go/src/github.com/docker/docker/vendor/github.com/vishvananda/netlink/addr_linux.go:274 +0x202
led 20 10:46:54 endrsmar dockerd[15500]: github.com/docker/docker/vendor/github.com/vishvananda/netlink.(*Handle).AddrList(0xc000177670, 0x55e2e8edb3c0, 0xc000c3e7e0, 0x2, 0x2, 0x1a4, 0x0, 0x0, 0xa300000000006c>
led 20 10:46:54 endrsmar dockerd[15500]:         /go/src/github.com/docker/docker/vendor/github.com/vishvananda/netlink/addr_linux.go:199 +0x213
led 20 10:46:54 endrsmar dockerd[15500]: github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge.(*bridgeInterface).addresses(0xc000e05860, 0x30, 0x30, 0xc00070d380, 0xc0007b3000, 0x10, 0x8,>
led 20 10:46:54 endrsmar dockerd[15500]:         /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge/interface.go:57 +0x52
led 20 10:46:54 endrsmar dockerd[15500]: github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge.setupBridgeIPv4(0xc000a804e0, 0xc000e05860, 0x0, 0x0)
led 20 10:46:54 endrsmar dockerd[15500]:         /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge/setup_ipv4.go:31 +0xc3
led 20 10:46:54 endrsmar dockerd[15500]: github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge.(*bridgeSetup).apply(0xc000f06750, 0xc000cc5400, 0x4)
led 20 10:46:54 endrsmar dockerd[15500]:         /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge/setup.go:17 +0x7c
led 20 10:46:54 endrsmar dockerd[15500]: github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge.(*driver).createNetwork(0xc0006f6480, 0xc000a804e0, 0x0, 0x0)
led 20 10:46:54 endrsmar dockerd[15500]:         /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge/bridge.go:809 +0x7fb
led 20 10:46:54 endrsmar dockerd[15500]: github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge.(*driver).populateNetworks(0xc0006f6480, 0x5, 0x55e2e7cfcf7a)
led 20 10:46:54 endrsmar dockerd[15500]:         /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge/bridge_store.go:62 +0x28d
led 20 10:46:54 endrsmar dockerd[15500]: github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge.(*driver).initStore(0xc0006f6480, 0xc000d673e0, 0x0, 0xc000825540)
led 20 10:46:54 endrsmar dockerd[15500]:         /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge/bridge_store.go:35 +0x211
led 20 10:46:54 endrsmar dockerd[15500]: github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge.(*driver).configure(0xc0006f6480, 0xc000d673e0, 0x55e2e8a04520, 0xc000d67110)
led 20 10:46:54 endrsmar dockerd[15500]:         /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge/bridge.go:439 +0x20d
led 20 10:46:54 endrsmar dockerd[15500]: github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge.Init(0x55e2e8ed9400, 0xc000d9ab00, 0xc000d673e0, 0xc000d673e0, 0x0)
led 20 10:46:54 endrsmar dockerd[15500]:         /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge/bridge.go:169 +0x9c
led 20 10:46:54 endrsmar dockerd[15500]: github.com/docker/docker/vendor/github.com/docker/libnetwork/drvregistry.(*DrvRegistry).AddDriver(...)
led 20 10:46:54 endrsmar dockerd[15500]:         /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drvregistry/drvregistry.go:72
led 20 10:46:54 endrsmar dockerd[15500]: github.com/docker/docker/vendor/github.com/docker/libnetwork.New(0xc0006f6400, 0x9, 0x10, 0xc000738d80, 0xc000c14c30, 0xc0006f6400, 0x9)
led 20 10:46:54 endrsmar dockerd[15500]:         /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/controller.go:221 +0x4f0
led 20 10:46:54 endrsmar dockerd[15500]: github.com/docker/docker/daemon.(*Daemon).initNetworkController(0xc00000c3c0, 0xc0003fa000, 0xc000c14c30, 0xc0002843c0, 0xc00000c3c0, 0xc000cd4448, 0xc000c14c30)
led 20 10:46:54 endrsmar dockerd[15500]:         /go/src/github.com/docker/docker/daemon/daemon_unix.go:855 +0xa9
led 20 10:46:54 endrsmar dockerd[15500]: github.com/docker/docker/daemon.(*Daemon).restore(0xc00000c3c0, 0xc000824a40, 0xc0001aa000)
led 20 10:46:54 endrsmar dockerd[15500]:         /go/src/github.com/docker/docker/daemon/daemon.go:490 +0x50b
led 20 10:46:54 endrsmar dockerd[15500]: github.com/docker/docker/daemon.NewDaemon(0x55e2e8f08780, 0xc000824a40, 0xc0003fa000, 0xc000738d80, 0x0, 0x0, 0x0)
led 20 10:46:54 endrsmar dockerd[15500]:         /go/src/github.com/docker/docker/daemon/daemon.go:1143 +0x2be7
led 20 10:46:54 endrsmar dockerd[15500]: main.(*DaemonCli).start(0xc0006eaa20, 0xc000260720, 0x0, 0x0)
led 20 10:46:54 endrsmar dockerd[15500]:         /go/src/github.com/docker/docker/cmd/dockerd/daemon.go:195 +0x743
led 20 10:46:54 endrsmar dockerd[15500]: main.runDaemon(...)
led 20 10:46:54 endrsmar dockerd[15500]:         /go/src/github.com/docker/docker/cmd/dockerd/docker_unix.go:13
led 20 10:46:54 endrsmar dockerd[15500]: main.newDaemonCommand.func1(0xc0000dcb00, 0xc0006ea9c0, 0x0, 0x3, 0x0, 0x0)
led 20 10:46:54 endrsmar dockerd[15500]:         /go/src/github.com/docker/docker/cmd/dockerd/docker.go:34 +0x7c
led 20 10:46:54 endrsmar dockerd[15500]: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).execute(0xc0000dcb00, 0xc00004e110, 0x3, 0x3, 0xc0000dcb00, 0xc00004e110)
led 20 10:46:54 endrsmar dockerd[15500]:         /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:850 +0x462
led 20 10:46:54 endrsmar dockerd[15500]: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0000dcb00, 0x0, 0x0, 0x10)
led 20 10:46:54 endrsmar dockerd[15500]:         /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:958 +0x34b
led 20 10:46:54 endrsmar dockerd[15500]: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).Execute(...)
led 20 10:46:54 endrsmar dockerd[15500]:         /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:895
led 20 10:46:54 endrsmar dockerd[15500]: main.main()
led 20 10:46:54 endrsmar dockerd[15500]:         /go/src/github.com/docker/docker/cmd/dockerd/docker.go:97 +0x191
led 20 10:46:54 endrsmar systemd[1]: docker.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
led 20 10:46:54 endrsmar systemd[1]: docker.service: Failed with result 'exit-code'.
led 20 10:46:54 endrsmar systemd[1]: Failed to start Docker Application Container Engine.
```

**Comment by joerhau** [comment]
I can reproduce the same issue, without VPN, too. Having Docker version 20.10.0, build eeddea2, installed on debian 10.7. Sometimes, the docker engine comes up without any issues, and sometimes it'll fail producing the segfault from above...
