### ISSUE TITLE
 docker-compose up is not working

### ISSUE THREAD

**Issue by PrafullaKumarSahu** [docker/for-linux#1227]
*  This is a bug report
*  This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior

 command should aggregates the output of each container.
### Actual behavior
Showing below error with verbose flag.
```
compose.config.config.find: Using configuration files: ./docker-compose.yml
docker.auth.auth.load_config: File doesn't exist
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.8.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 61, in main
    command()
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 110, in perform_command
    project = project_from_options('.', options)
  File "/usr/lib/python2.7/dist-packages/compose/cli/command.py", line 35, in project_from_options
    environment=environment
  File "/usr/lib/python2.7/dist-packages/compose/cli/command.py", line 110, in get_project
    host=host, environment=environment
  File "/usr/lib/python2.7/dist-packages/compose/cli/command.py", line 85, in get_client
    version_info = six.iteritems(client.version())
  File "/usr/lib/python2.7/dist-packages/docker/api/daemon.py", line 76, in version
    return self._result(self._get(url), json=True)
  File "/usr/lib/python2.7/dist-packages/docker/utils/decorators.py", line 47, in inner
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/docker/client.py", line 140, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 492, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 480, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 588, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=2375): Max retries exceeded with url: /v1.22/version (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fb6d88d7c90>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

### Steps to reproduce the behavior
Nothing specific, just run docker-compose up
**Output of `docker version`:**

```
Docker version 18.09.7, build 2d0083d
```

**Output of `docker info`:**

```
Cannot connect to the Docker daemon at tcp://127.0.0.1:2375. Is the docker daemon running?
```
OS- Ubuntu 18.4 local system

**Comment by thaJeztah** [comment]
Error indicates the docker daemon either isn't running, is running on another address, or the current user doesn't have permissions to access it.

Note that docker 18.09 has reached EOL, and I would recommend updating to a currently maintained version to not miss out on (security) updates.


I'm closing because of the above, but feel free to continue the conversation
