### ISSUE TITLE
sudo docker-compose up -d doesn't work

### ISSUE THREAD

**Issue by RomaPrograms** [docker/for-linux#1241]
I have linux ubuntu version: 20.04.2 LTS
docker version: 20.10.6
docker-compose version 1.28.5

When run command: `sudo docker-compose up -d`
The answer is:
`Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 80, in main
  File "compose/cli/main.py", line 192, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper
  File "compose/cli/main.py", line 1165, in up
  File "compose/cli/main.py", line 1161, in up
  File "compose/project.py", line 664, in up
  File "compose/service.py", line 357, in ensure_image_exists
  File "compose/service.py", line 1269, in pull
  File "compose/progress_stream.py", line 99, in get_digest_from_pull
  File "compose/service.py", line 1236, in _do_pull
  File "docker/api/image.py", line 411, in pull
  File "docker/auth.py", line 48, in get_config_header
  File "docker/auth.py", line 324, in resolve_authconfig
  File "docker/auth.py", line 235, in resolve_authconfig
  File "docker/auth.py", line 262, in _resolve_authconfig_credstore
  File "docker/auth.py", line 287, in _get_store_instance
  File "docker/credentials/store.py", line 25, in __init__
docker.credentials.errors.InitializationError: docker-credential-desktop.exe not installed or not available in PATH
[29187] Failed to execute script docker-compose`

**Comment by thaJeztah** [comment]
From the error, I suspect you have a `~/.docker/config.json` that has the windows credentials helper for Docker Desktop set for authentication; https://docs.docker.com/engine/reference/commandline/login/#credential-helpers

```
docker-credential-desktop.exe not installed or not available in PATH
[29187] Failed to execute script docker-compose
```

**Comment by gromula** [comment]
I have same problem with docker-compose.
