### ISSUE TITLE
Docker rm hangs: grouting stuck in runtime_SemacquireMutex (possible deadlock)

### ISSUE THREAD

**Issue by pranavadn** [docker/for-linux#1319]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior

docker rm should delete the container
### Actual behavior

docker rm hangs, gets stuck and does not complete
### Steps to reproduce the behavior

It was found that docker rm of a container was not completing. 
sudo docker rm -f afbbb2668c2d
^C

"docker inspect" and "docker exec" were also found to be not completing for the same container. 

 "curl --unix-socket /var/run/docker.sock http://./debug/pprof/goroutine?debug=2" output shows that for each "docker rm" or "docker exec" or "docker inspect", a go routine is created that gets stuck in acquiring a semaphore in runtime_SemacquireMutex. 

goroutine 673677 [semacquire, 1130 minutes]:
sync.runtime_SemacquireMutex(0xc0009a1404, 0xc001857600, 0x1)
/usr/local/go/src/runtime/sema.go:71 +0x49
sync.(*Mutex).lockSlow(0xc0009a1400)
/usr/local/go/src/sync/mutex.go:138 +0xfe
sync.(*Mutex).Lock(...)
/usr/local/go/src/sync/mutex.go:81
github.com/docker/docker/container.(*State).GetPID(0xc0009a1400, 0xc000a7d2a0)
/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/container/state.go:248 +0x7b
github.com/docker/docker/daemon.killProcessDirectly(0xc000113440, 0x0, 0x0)
/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/container_operations_unix.go:346 +0x14e
github.com/docker/docker/daemon.(*Daemon).Kill(0xc00000c3c0, 0xc000113440, 0x0, 0x0)
/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/kill.go:152 +0x19b
github.com/docker/docker/daemon.(Daemon).*cleanupContainer(0xc00000c3c0, 0xc000113440, 0x1, 0xc000113440, 0x0)
/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/delete.go:90 +0x387
github.com/docker/docker/daemon.(Daemon).*ContainerRm(0xc00000c3c0, 0xc000f400d9, 0xc, 0xc000bc81c6, 0x0, 0x0)
/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/delete.go:45 +0x181
github.com/docker/docker/api/server/router/container.(containerRouter).*deleteContainers(0xc0009d0ec0, 0x55df6c2823c0, 0xc0011ecae0, 0x55df6c273400, 0xc0004008c0, 0xc001794800, 0xc0011eca20, 0xc0001b8001, 0xc000b8e840)

Looks like the whole behaviour gets triggered with "docker rm". Before that, docker inspect would be working. A docker rm on the working container gets it into this state. Post that docker inspect and docker exec also hang in acquiring the lock.

**Output of `docker version`:**
```
Docker version 19.03.12, build 48a66213fe
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 12
  Running: 7
  Paused: 0
  Stopped: 5
 Images: 13
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1160.42.2.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 32
 Total Memory: 62.66GiB
 Name: watchmenmagpch-local-bqkp74907548-node-3
 ID: VNHM:52GA:UMCL:CDRZ:ITFH:NUA7:HZSF:EZKD:KRZW:DMQH:J6KC:HK6H
 Docker Root Dir: /home_cohesity_data/disks/sdd2_b109fd0e-6a80-4114-a2c9-ca4ab8207c5c/athena/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  localhost:25684
  localhost:25699
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by cwbusacker** [comment]
I am having this same issue on `balena` devices which uses docker. The only way to fix it is to restart the docker/balena engine.
