### ISSUE TITLE
Docker stack not entirely booting

### ISSUE THREAD

**Issue by JPZ13** [docker/for-linux#23]
### Expected behavior
All lines in `docker stack ps TEST` should be running
### Actual behavior
Two are in shutdown mode
### Information

  - Linux distro: Ubuntu 16.04 Xenial
  - Docker CE version: 17.06.0-ce-rc3
  - [Compose File](https://raw.githubusercontent.com/dockersamples/example-voting-app/master/docker-stack.yml)
  - Machine Public IP: 54.202.191.23

### Steps to reproduce the behavior

  1. SSH into the above IP
  2. `wget https://raw.githubusercontent.com/dockersamples/example-voting-app/master/docker-stack.yml`
  3. `sudo docker stack deploy --compose-file docker-stack.yml TEST`
  4. `sudo docker stack ps TEST`

**Comment by FrenchBen** [comment]
Looks like a compose file/service issue more than actual swarm issue:
```
docker service logs k3z90hwq3tn7
TEST_worker.1.k3z90hwq3tn7@ip-172-31-11-7    | System.AggregateException: One or more errors occurred. (No such device or address) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: No such device or address
TEST_worker.1.k3z90hwq3tn7@ip-172-31-11-7    |    at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
TEST_worker.1.k3z90hwq3tn7@ip-172-31-11-7    |    at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
TEST_worker.1.k3z90hwq3tn7@ip-172-31-11-7    |    at System.Net.Dns.<>c.<GetHostAddressesAsync>b__14_1(IAsyncResult asyncResult)
TEST_worker.1.k3z90hwq3tn7@ip-172-31-11-7    |    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
TEST_worker.1.k3z90hwq3tn7@ip-172-31-11-7    |    --- End of inner exception stack trace ---
TEST_worker.1.k3z90hwq3tn7@ip-172-31-11-7    |    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
TEST_worker.1.k3z90hwq3tn7@ip-172-31-11-7    |    at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
TEST_worker.1.k3z90hwq3tn7@ip-172-31-11-7    |    at Npgsql.NpgsqlConnector.RawOpen(NpgsqlTimeout timeout)
TEST_worker.1.k3z90hwq3tn7@ip-172-31-11-7    |    at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout)
TEST_worker.1.k3z90hwq3tn7@ip-172-31-11-7    |    at Npgsql.ConnectorPool.Allocate(NpgsqlConnection conn, NpgsqlTimeout timeout)
TEST_worker.1.k3z90hwq3tn7@ip-172-31-11-7    |    at Npgsql.NpgsqlConnection.OpenInternal()
TEST_worker.1.k3z90hwq3tn7@ip-172-31-11-7    |    at Worker.Program.OpenDbConnection(String connectionString) in /code/src/Worker/Program.cs:line 74
TEST_worker.1.k3z90hwq3tn7@ip-172-31-11-7    |    at Worker.Program.Main(String[] args) in /code/src/Worker/Program.cs:line 19
TEST_worker.1.k3z90hwq3tn7@ip-172-31-11-7    | ---> (Inner Exception #0) System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: No such device or address
TEST_worker.1.k3z90hwq3tn7@ip-172-31-11-7    |    at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
TEST_worker.1.k3z90hwq3tn7@ip-172-31-11-7    |    at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
TEST_worker.1.k3z90hwq3tn7@ip-172-31-11-7    |    at System.Net.Dns.<>c.<GetHostAddressesAsync>b__14_1(IAsyncResult asyncResult)
TEST_worker.1.k3z90hwq3tn7@ip-172-31-11-7    |    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)<---
```

**Comment by thaJeztah** [comment]
Yes, looks like this is not an issue in the docker codebase, but possibly with that example. May be worth opening an issue at https://github.com/dockersamples/example-voting-app/issues if you're still having this.

Let me close the issue here, but feel free to continue the conversation
