### ISSUE TITLE
Docker crash at swarm startup

### ISSUE THREAD

**Issue by delacko** [docker/for-linux#286]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior
After rebooting a 3 node swarm cluster it is expected that docker starts working on all 3 nodes.

### Actual behavior
After rebooting all 3 nodes in docker swarm cluster docker is active on only 1 node and it crashes with SIGSEGV on other 2 nodes during.
I have done restart of these server a lot of times and after this happens I cannot recover it. 
Prior to this problem happening for the first time, docker failed because of  OOM killer killing some of its process - as it wasn't consider important at the time I rebooted all 3 nodes of the cluster.

After the problem appeared for the first time I tried to start docker on any of the 2 nodes that have failed  with "service docker start" same process happens as after boot - shortly after leader is elected new docker instance crashes.
```
Logs from the docker that tries to join the cluster:

Apr 20 11:16:42 test-core1 dockerd[2045]: time="2018-04-20T11:16:42.854989212+02:00" level=info msg="59c75ed43076d4e3 [logterm: 649, index: 704762] sent MsgVote request to 2bc9f2031430e998 at term 650" module=raft node.id=j11fp57zboev9st1l873nph1g
Apr 20 11:16:42 test-core1 dockerd[2045]: time="2018-04-20T11:16:42.855539462+02:00" level=info msg="59c75ed43076d4e3 [logterm: 649, index: 704762] sent MsgVote request to 4b1dee8f68faefc1 at term 650" module=raft node.id=j11fp57zboev9st1l873nph1g
Apr 20 11:16:42 test-core1 dockerd[2045]: time="2018-04-20T11:16:42.857275241+02:00" level=error msg="error sending message to peer" error="rpc error: code = Unavailable desc = grpc: the connection is unavailable"
Apr 20 11:16:42 test-core1 dockerd[2045]: time="2018-04-20T11:16:42.866409595+02:00" level=info msg="59c75ed43076d4e3 received MsgVoteResp from 4b1dee8f68faefc1 at term 650" module=raft node.id=j11fp57zboev9st1l873nph1g
Apr 20 11:16:42 test-core1 dockerd[2045]: time="2018-04-20T11:16:42.866965592+02:00" level=info msg="59c75ed43076d4e3 [quorum:2] has received 2 MsgVoteResp votes and 0 vote rejections" module=raft node.id=j11fp57zboev9st1l873nph1g
Apr 20 11:16:42 test-core1 dockerd[2045]: time="2018-04-20T11:16:42.868146428+02:00" level=info msg="59c75ed43076d4e3 became leader at term 650" module=raft node.id=j11fp57zboev9st1l873nph1g
Apr 20 11:16:42 test-core1 dockerd[2045]: time="2018-04-20T11:16:42.868523177+02:00" level=info msg="raft.node: 59c75ed43076d4e3 elected leader 59c75ed43076d4e3 at term 650" module=raft node.id=j11fp57zboev9st1l873nph1g
Apr 20 11:16:42 test-core1 dockerd[2045]: time="2018-04-20T11:16:42.870031183+02:00" level=error msg="error sending message to peer" error="rpc error: code = Unavailable desc = grpc: the connection is unavailable"
Apr 20 11:16:42 test-core1 dockerd[2045]: time="2018-04-20T11:16:42.874611404+02:00" level=error msg="error creating cluster object" error="name conflicts with an existing object" module=node node.id=j11fp57zboev9st1l873nph1g
Apr 20 11:16:42 test-core1 dockerd[2045]: time="2018-04-20T11:16:42.877923749+02:00" level=error msg="failed to create predefined network bridge" error="name conflicts with an existing object" module=node node.id=j11fp57zboev9st1l873nph1g
Apr 20 11:16:42 test-core1 dockerd[2045]: time="2018-04-20T11:16:42.877997208+02:00" level=error msg="failed to create predefined network host" error="name conflicts with an existing object" module=node node.id=j11fp57zboev9st1l873nph1g
Apr 20 11:16:42 test-core1 dockerd[2045]: time="2018-04-20T11:16:42.878561546+02:00" level=info msg="dispatcher starting" module=dispatcher node.id=j11fp57zboev9st1l873nph1g
Apr 20 11:16:42 test-core1 dockerd[2045]: time="2018-04-20T11:16:42.902355891+02:00" level=error msg="failed allocating network po71o1fi43j09ft7tco9cpycq during init" error="failed allocating pools and gateway IP for network po71o1fi43j09ft7tco9cpycq: Address already in use" module=node node.id=j11fp57zboev9st1l873nph1g
Apr 20 11:16:43 test-core1 dockerd[2045]: time="2018-04-20T11:16:43.506613602+02:00" level=info msg="worker nrp7lvnq68s1tkm1d2wa1dxxv was successfully registered" method="(*Dispatcher).register"
Apr 20 11:16:43 test-core1 dockerd[2045]: time="2018-04-20T11:16:43.508283484+02:00" level=info msg="worker j11fp57zboev9st1l873nph1g was successfully registered" method="(*Dispatcher).register"
Apr 20 11:16:43 test-core1 dockerd[2045]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 20 11:16:43 test-core1 dockerd[2045]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x71 pc=0x55a2c11942c8]
Apr 20 11:16:43 test-core1 dockerd[2045]: goroutine 248 [running]:
Apr 20 11:16:43 test-core1 dockerd[2045]: github.com/docker/docker/daemon/cluster/executor/container.(*executor).Configure(0xc4201bc880, 0x7f1f2f2870b0, 0xc420a19bc0, 0xc423652c80, 0xf, 0xa)
Apr 20 11:16:43 test-core1 dockerd[2045]: #011/go/src/github.com/docker/docker/daemon/cluster/executor/container/executor.go:144 +0x138
Apr 20 11:16:43 test-core1 dockerd[2045]: github.com/docker/docker/vendor/github.com/docker/swarmkit/agent.(*Agent).handleSessionMessage(0xc420956180, 0x7f1f2f2870b0, 0xc420a19bc0, 0xc4211d6900, 0xc420f8e370, 0x0, 0xc420a198c0)
Apr 20 11:16:43 test-core1 dockerd[2045]: #011/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/agent/agent.go:408 +0x1fe
Apr 20 11:16:43 test-core1 dockerd[2045]: github.com/docker/docker/vendor/github.com/docker/swarmkit/agent.(*Agent).run(0xc420956180, 0x7f1f2f2870b0, 0xc420a19bc0)
Apr 20 11:16:43 test-core1 dockerd[2045]: #011/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/agent/agent.go:294 +0x1710
Apr 20 11:16:43 test-core1 dockerd[2045]: created by github.com/docker/docker/vendor/github.com/docker/swarmkit/agent.(*Agent).Start.func1
Apr 20 11:16:43 test-core1 dockerd[2045]: #011/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/agent/agent.go:83 +0x8a
Apr 20 11:16:43 test-core1 systemd[1]: docker.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 20 11:16:43 test-core1 systemd[1]: Failed to start Docker Application Container Engine.
```

### Steps to reproduce the behavior

After cluster comes into this invalid state behaviour is easy to reproduce by trying to start docker on one node - it will crash during startup.

**Output of `docker version`:**

```
# docker version
Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	0520e24
 Built:	Wed Mar 21 23:10:01 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	0520e24
  Built:	Wed Mar 21 23:08:31 2018
  OS/Arch:	linux/amd64
  Experimental:	false

```

**Output of `docker info`:**

```
# docker info
Containers: 8
 Running: 0
 Paused: 0
 Stopped: 8
Images: 9
Server Version: 18.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: pending
 NodeID: nrp7lvnq68s1tkm1d2wa1dxxv
 Error: rpc error: code = Unknown desc = The swarm does not have a leader. It's possible that too few managers are online. Make sure more than half of the managers are online.
 Is Manager: true
 Node Address: 10.1.3.131
 Manager Addresses:
  10.1.3.128:2337
  10.1.3.129:2377
  10.1.3.131:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-119-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.828GiB
Name: test-core3
ID: EBW7:5IVM:WY7T:74RD:TG7H:G2Z3:YQVY:TQF3:EOZ7:BVBB:L6O5:6UBS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

 KVM VMs with 4 GB RAM, 1 CPU core.

**Comment by michaelzhang02010479** [comment]
how fix it, I got an same error

**Comment by ChristophSchranz** [comment]
I had the same issue:

> Mai 27 11:35:00 il081 systemd[1]: docker.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mai 27 11:35:00 il081 systemd[1]: docker.service: Failed with result 'exit-code'.
Mai 27 11:35:00 il081 systemd[1]: Stopped Docker Application Container Engine.
Mai 27 11:35:09 il081 systemd[1]: docker.service: Start request repeated too quickly.
Mai 27 11:35:09 il081 systemd[1]: docker.service: Failed with result 'exit-code'.
Mai 27 11:35:09 il081 systemd[1]: Failed to start Docker Application Container Engine.

In the logs:
> Mai 27 11:35:00 il081 dockerd[15547]: time="2019-05-27T11:35:00.388073460+02:00" level=info msg="1263e916cb9f6beb is starting a new election at term 374" module=raft node.id=ndetrvgrj0br6y01fxbi8kb2w
Mai 27 11:35:00 il081 dockerd[15547]: time="2019-05-27T11:35:00.388138077+02:00" level=info msg="1263e916cb9f6beb became candidate at term 375" module=raft node.id=ndetrvgrj0br6y01fxbi8kb2w
Mai 27 11:35:00 il081 dockerd[15547]: time="2019-05-27T11:35:00.388162393+02:00" level=info msg="1263e916cb9f6beb received MsgVoteResp from 1263e916cb9f6beb at term 375" module=raft node.id=ndetrvgrj0br6y01fxbi8kb2w
Mai 27 11:35:00 il081 dockerd[15547]: time="2019-05-27T11:35:00.388184443+02:00" level=info msg="1263e916cb9f6beb became leader at term 375" module=raft node.id=ndetrvgrj0br6y01fxbi8kb2w
Mai 27 11:35:00 il081 dockerd[15547]: time="2019-05-27T11:35:00.388198545+02:00" level=info msg="raft.node: 1263e916cb9f6beb elected leader 1263e916cb9f6beb at term 375" module=raft node.id=ndetrvgrj0br6y01fxbi8kb2w
Mai 27 11:35:00 il081 dockerd[15547]: time="2019-05-27T11:35:00.389274203+02:00" level=error msg="error creating cluster object" error="name conflicts with an existing object" module=node node.id=ndetrvgrj0br6y01fxbi8kb2w
Mai 27 11:35:00 il081 dockerd[15547]: time="2019-05-27T11:35:00.389429292+02:00" level=info msg="leadership changed from not yet part of a raft cluster to ndetrvgrj0br6y01fxbi8kb2w" module=node node.id=ndetrvgrj0br6y01fxbi8kb2w
Mai 27 11:35:00 il081 dockerd[15547]: time="2019-05-27T11:35:00.389609121+02:00" level=info msg="dispatcher starting" module=dispatcher node.id=ndetrvgrj0br6y01fxbi8kb2w
Mai 27 11:35:00 il081 dockerd[15547]: time="2019-05-27T11:35:00.402247707+02:00" level=error msg="IPAM failure while releasing IP address 10.0.2.7/24" error="invalid pool id: "
Mai 27 11:35:00 il081 dockerd[15547]: time="2019-05-27T11:35:00.402424273+02:00" level=error msg="error deallocating attachment for network ynwmge5g65r70s2j5jv00y5nd on node ndetrvgrj0br6y01fxbi8kb2w" error="could not find network allocator state for network ynwmge5g65r70s2j5jv00y5nd" module=node node.id=ndetrvgrj0br6y01f
Mai 27 11:35:00 il081 dockerd[15547]: time="2019-05-27T11:35:00.402459941+02:00" level=error msg="error deallocating attachment for network k2uy2osejy3gyh2ddwr3gq08y on node ndetrvgrj0br6y01fxbi8kb2w" error="could not find network allocator state for network k2uy2osejy3gyh2ddwr3gq08y" module=node node.id=ndetrvgrj0br6y01f
Mai 27 11:35:00 il081 dockerd[15547]: panic: runtime error: invalid memory address or nil pointer dereference
Mai 27 11:35:00 il081 dockerd[15547]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x564d19947b3c]
Mai 27 11:35:00 il081 dockerd[15547]: goroutine 371 [running]:
Mai 27 11:35:00 il081 dockerd[15547]: github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator.(*Allocator).allocateNode(0xc42242e380, 0x564d1a6fbe20, 0xc420c62f00, 0xc4231ec280, 0x0, 0xc421a5dea0, 0x3, 0x4, 0xc420e7ab01)
Mai 27 11:35:00 il081 dockerd[15547]:         /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator/network.go:1045 +0x53c
Mai 27 11:35:00 il081 dockerd[15547]: github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator.(*Allocator).allocateNodes(0xc42242e380, 0x564d1a6fbe20, 0xc420c62f00, 0x0, 0x0, 0x0)
Mai 27 11:35:00 il081 dockerd[15547]:         /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator/network.go:477 +0x1c0
Mai 27 11:35:00 il081 dockerd[15547]: github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator.(*Allocator).doNetworkInit(0xc42242e380, 0x564d1a6fbe20, 0xc420c62f00, 0x0, 0x0)
Mai 27 11:35:00 il081 dockerd[15547]:         /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator/network.go:154 +0x4da
Mai 27 11:35:00 il081 dockerd[15547]: github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator.(*Allocator).(github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator.doNetworkInit)-fm(0x564d1a6fbe20, 0xc420c62f00, 0xc, 0xc)
Mai 27 11:35:00 il081 dockerd[15547]:         /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator/allocator.go:105 +0x40
Mai 27 11:35:00 il081 dockerd[15547]: github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator.(*Allocator).init(0xc42242e380, 0x564d1a6fbe20, 0xc420c62f00, 0xc420e89800, 0x0, 0x0, 0xc4228d49b0, 0x0)
Mai 27 11:35:00 il081 dockerd[15547]:         /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator/allocator.go:174 +0x4dd
Mai 27 11:35:00 il081 dockerd[15547]: github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator.(*Allocator).Run.func2(0x0, 0x0)
Mai 27 11:35:00 il081 dockerd[15547]:         /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator/allocator.go:122 +0xbc
Mai 27 11:35:00 il081 dockerd[15547]: github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator.(*Allocator).Run(0xc42242e380, 0x564d1a6fbe20, 0xc4208f0140, 0x0, 0x0)
Mai 27 11:35:00 il081 dockerd[15547]:         /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator/allocator.go:142 +0x4e1
Mai 27 11:35:00 il081 dockerd[15547]: github.com/docker/docker/vendor/github.com/docker/swarmkit/manager.(*Manager).becomeLeader.func6(0x564d1a6fbe20, 0xc4208f0140, 0xc42242e380)
Mai 27 11:35:00 il081 dockerd[15547]:         /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/manager.go:1048 +0x45
Mai 27 11:35:00 il081 dockerd[15547]: created by github.com/docker/docker/vendor/github.com/docker/swarmkit/manager.(*Manager).becomeLeader
Mai 27 11:35:00 il081 dockerd[15547]:         /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/manager.go:1047 +0xf34
Mai 27 11:35:00 il081 systemd[1]: docker.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mai 27 11:35:00 il081 systemd[1]: docker.service: Failed with result 'exit-code'.
Mai 27 11:35:00 il081 systemd[1]: Stopped Docker Application Container Engine.
Mai 27 11:35:09 il081 systemd[1]: docker.service: Start request repeated too quickly.
Mai 27 11:35:09 il081 systemd[1]: docker.service: Failed with result 'exit-code'.
Mai 27 11:35:09 il081 systemd[1]: Failed to start Docker Application Container Engine.
lines 964-1001/1001 (END)

Unfortunately, I had to remove the docker container directory, reinstall docker and reinit the docker swarm...

Remove containers:
`sudo service docker stop`
`sudo rm -r /var/lib/docker/containers/`

Docker (de-)installation CLI commands: 
https://docs.docker.com/install/linux/docker-ce/ubuntu/

Maybe, you get it less invasiv!

My docker version:
> $ docker version
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:35:57 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false
