### ISSUE TITLE
Using Popen inside a python script says file not found

### ISSUE THREAD

**Issue by munawarb** [docker/for-linux#297]
### Expected behavior
When using `subprocess.run`, the underlying `popen` interface should find and execute the file, as it does on standard Linux.

### Actual behavior
I get an error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "startflood.py", line 10, in spawnNewProgram
    program = run(["./testexecutable"])
  File "/usr/local/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.6/subprocess.py", line 1333, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: './testexecutable'
```

### Steps to reproduce the behavior

- Place a Python script and some executable in the same directory. The Python script can contain something like this:
```python
from subprocess import run
run(["./someexecutable"])
```
- Create a dockerfile:
```
FROM python:3.6.2-alpine3.6

WORKDIR /src

COPY files_dir /src/

COPY run.sh /src/

RUN apk add --update bash

RUN chmod +x /src/run.sh
run chmod +x /src/someexecutable

RUN apk add --no-cache gcc musl-dev

ENTRYPOINT /src/run.sh
```
- Create the run.sh file:
```
#!/bin/bash +e
chmod +x /src/someexecutable
cd /src
python3 somescript.py
```
- Python will throw a file not found error, when this same setup works on standard Linux outside of docker.
- I have also tried providing the full path to `someexecutable`, changing the script to this line: `run(["/src/someexecutable"])`, but still I get the file not found error.
- Running `print(os.path.listdir("."))` shows the file someexecutable actually exists in the working directory.

**Output of `docker version`:**

```
Docker version 18.03.1-ce, build 9ee9f40
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 135
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-119-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 64
Total Memory: 62.8GiB
Name: iot
ID: FLF4:O5AV:CG7R:QQ6C:OFC6:4F7M:DPY2:WT7D:OOCI:2OQ2:7BUN:IHCL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
munawar@iot:~$ 
```

**Comment by euanh** [comment]
The problem is that `someexecutable` was built on your host system and is linked against GNU libc, but in the Alpine container you have `musl`.   See this issue for more details: https://github.com/gliderlabs/docker-alpine/issues/219

Inside the container:
```
/src # apk add file
/src # file someexecutable
someexecutable: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=b4f1d3527a0e8d5ee62b347c1b4b3ca51263ef70, not stripped
/src # ls /lib64/ld-linux-x86-64.so.2
ls: /lib64/ld-linux-x86-64.so.2: No such file or directory
# ./somexecutable
sh: ./someexecutable: not found
```
You can either rebuild your binary in the Dockerfile (`RUN gcc somexecutable.c -o someexecutable`).   You are already installing `gcc` and `musl-devel` in your Dockerfile, so you should have everything you need to rebuild.
```
# gcc hello.c -o someexecutable
# file someexecutable
someexecutable: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-x86_64.so.1, with debug_info, not stripped
# ./someexecutable
Hello, world!
```
Alternatively, if your binary is simple and you don't want to rebuild it during the container build, you can try `apk add libc6-compat` to add a GNU libc compatiblity layer.
