### ISSUE TITLE
Gelf logging driver sends empty short_message if empty line is logged

### ISSUE THREAD

**Issue by marcinwaldowski** [docker/for-linux#354]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior

Gelf logging driver should not send message to GELF server if `short_message` if empty.

### Actual behavior

Gelf logging driver sends empty `short_message` if empty line is logged. It ends up with following stacktrace in graylog server (it looks like message is rejected):

```
2018-07-04 06:56:16,298 ERROR: org.graylog2.shared.buffers.processors.DecodingProcessor - Error processing message RawMessage{id=58c3f640-7f57-11e8-9eb6-0242ac120004, journalOffset=45, codec=gelf, payloadSize=402, timestamp=2018-07-04T06:56:16.292Z, remoteAddress=/192.168.0.112:56448}
java.lang.IllegalArgumentException: GELF message <58c3f640-7f57-11e8-9eb6-0242ac120004> (received from <192.168.0.112:56448>) has empty mandatory "short_message" field.
	at org.graylog2.inputs.codecs.GelfCodec.validateGELFMessage(GelfCodec.java:252) ~[graylog.jar:?]
	at org.graylog2.inputs.codecs.GelfCodec.decode(GelfCodec.java:134) ~[graylog.jar:?]
	at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:150) ~[graylog.jar:?]
	at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:91) [graylog.jar:?]
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:74) [graylog.jar:?]
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:42) [graylog.jar:?]
	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) [graylog.jar:?]
	at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

### Steps to reproduce the behavior

- setup Graylog server with UDP input listening on standard port 12201
- execute `docker run --log-driver=gelf --log-opt gelf-address=udp://192.168.0.112:12201 --log-opt gelf-compression-type=none busybox echo ""`
- check Graylog server logs

**Output of `docker version`:**

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Comment by jeisonmp** [comment]
+up

**Comment by hangstl** [comment]
Would, as a workaround, help to add this to Logstash filters?
...
if [message] =~ /^\s*$/ {
  drop { }
...

**Comment by mahnunchik** [comment]
any news?

**Comment by ccandreva** [comment]
Can someone clarify the scope of this bug ?  Is it generating a GELF message when it should do nothing (ie, an empty log line) resulting in noise in the Graylog log file, or is there data loss because of the missing short_message field ?

**Comment by marcinwaldowski** [comment]
Is it generating a GELF message on empty line when it should do nothing. It results in noise in the Graylog log file because "short_message" field cannot be empty.

**Comment by mknj** [comment]
Is there any workaround for this? I just notices a 91GB logfile for my graylog server because my gitlab instance constantly logs empty lines.

**Comment by thaJeztah** [comment]
I think this should be fixed by https://github.com/moby/moby/pull/40234 / https://github.com/docker/engine/pull/427, which no longer sends empty log messages, and is in docker 19.03.6 and up.
