### ISSUE TITLE
Docker start failing

### ISSUE THREAD

**Issue by shettyh** [docker/for-linux#438]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
Docker should start normally

### Actual behavior
Docker is not starting. On `reboot` of the machine issue got resolved.

### Steps to reproduce the behavior
NA

### Logs

```
time="2018-08-17T11:49:42+05:30" level=info msg="loading plugin "io.containerd.grpc.v1.introspection"..." module=containerd type=io.containerd.grpc.v1
time="2018-08-17T11:49:42+05:30" level=info msg=serving... address="/var/run/docker/containerd/docker-containerd-debug.sock" module="containerd/debug"
time="2018-08-17T11:49:42+05:30" level=info msg=serving... address="/var/run/docker/containerd/docker-containerd.sock" module="containerd/grpc"
time="2018-08-17T11:49:42+05:30" level=info msg="containerd successfully booted in 0.017711s" module=containerd
time="2018-08-17T11:49:42.766631498+05:30" level=info msg="[graphdriver] using prior storage driver: overlay2"
time="2018-08-17T11:49:43.054522591+05:30" level=info msg="Graph migration to content-addressability took 0.00 seconds"
time="2018-08-17T11:49:43.054738881+05:30" level=warning msg="Your kernel does not support swap memory limit"
time="2018-08-17T11:49:43.054772666+05:30" level=warning msg="Your kernel does not support cgroup rt period"
time="2018-08-17T11:49:43.054781936+05:30" level=warning msg="Your kernel does not support cgroup rt runtime"
time="2018-08-17T11:49:43.055240055+05:30" level=info msg="Loading containers: start."
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x55de5ce24dcd]
goroutine 7325 [running]:
github.com/docker/docker/vendor/github.com/containerd/containerd/cio.openFifos(0x55de5ee8e160, 0xc42025eb80, 0xc42025eb40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
#011/go/src/github.com/docker/docker/vendor/github.com/containerd/containerd/cio/io_unix.go:95 +0x3dd
github.com/docker/docker/vendor/github.com/containerd/containerd/cio.NewDirectIO(0x55de5ee8e160, 0xc42025eb80, 0xc42025eb40, 0xc420514540, 0x5b, 0xc4202778f0)
#011/go/src/github.com/docker/docker/vendor/github.com/containerd/containerd/cio/io_unix.go:113 +0xdd
github.com/docker/docker/libcontainerd.(*client).Restore.func3(0xc42025eb40, 0xc42025eb40, 0x3, 0xc420514540, 0x5b)
#011/go/src/github.com/docker/docker/libcontainerd/client_daemon.go:176 +0x5e
github.com/docker/docker/vendor/github.com/containerd/containerd.attachExistingIO(0xc4220e20a0, 0xc42214a8d0, 0xc420014038, 0xc420454a20, 0x0, 0x0)
#011/go/src/github.com/docker/docker/vendor/github.com/containerd/containerd/container.go:308 +0x251
github.com/docker/docker/vendor/github.com/containerd/containerd.(*container).loadTask(0xc420454960, 0x55de5ee8e1a0, 0xc420014038, 0xc42214a8d0, 0x30, 0x55de5e281f40, 0x1, 0xc42214a8d0)
#011/go/src/github.com/docker/docker/vendor/github.com/containerd/containerd/container.go:275 +0x297
github.com/docker/docker/vendor/github.com/containerd/containerd.(*container).Task(0xc420454960, 0x55de5ee8e1a0, 0xc420014038, 0xc42214a8d0, 0x40, 0x55de5ee99480, 0xc420454960, 0x0)
#011/go/src/github.com/docker/docker/vendor/github.com/containerd/containerd/container.go:144 +0x4b
github.com/docker/docker/libcontainerd.(*client).Restore(0xc420148460, 0x55de5ee8e1a0, 0xc420014038, 0xc420726c40, 0x40, 0xc420506040, 0xc420536c00, 0x0, 0x0, 0x0)
#011/go/src/github.com/docker/docker/libcontainerd/client_daemon.go:182 +0x592
github.com/docker/docker/daemon.(*Daemon).restore.func1(0xc420ca4220, 0xc420444240, 0xc420ca4230, 0xc420d9c930, 0xc420d9c900, 0xc420d9c8d0, 0xc42009b440)
#011/go/src/github.com/docker/docker/daemon/daemon.go:238 +0x3ec
created by github.com/docker/docker/daemon.(*Daemon).restore
#011/go/src/github.com/docker/docker/daemon/daemon.go:216 +0xfb8
panic: runtime error: invalid memory address or nil pointer dereference

```

**Output of `docker version`:**

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: false

```

**Output of `docker info`:**

```
Containers: 30
 Running: 26
 Paused: 0
 Stopped: 4
Images: 220
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: nvidia runc
Default Runtime: nvidia
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871-dirty (expected: 4fc53a81fb7c994640722ac585fa9ca548971871)
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.13.0-43-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.3GiB
Name: drone-pc
ID: DHEQ:XRBW:KA2Z:BMDA:JS4H:LOUE:JWFP:MKNY:QCQ7:WTQE:W5OH:72Z2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
HTTP Proxy: http://10.158.100.6:8080/
HTTPS Proxy: http://10.158.100.6:8080/
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

** Environment **
Baremetal

**Comment by g3d** [comment]
Had similar behaviour on fresh ubuntu 18.04 installation, fixed by upgrading to focal & switching to docker.io: https://linuxconfig.org/how-to-install-docker-on-ubuntu-20-04-lts-focal-fossa
```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
# uname -a
Linux pivorak-production-eu 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
# docker info
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 19.03.6
 Storage Driver: aufs
  Root Dir: /var/lib/docker/aufs
  Backing Filesystem: extfs
  Dirs: 0
  Dirperm1 Supported: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 35bd7a5f69c13e1563af8a93431411cd9ecf5021
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-88-generic
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 1.946GiB
 Name: pivorak-production-eu
 ID: T2NY:32NS:TMLC:DK6M:LPC6:ZXZM:M4LL:K3FQ:J2BO:IZC7:LFEF:VTNW
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: the aufs storage-driver is deprecated, and will be removed in a future release.
```

New:
```
# uname -a
Linux pivorak-production-eu 5.4.0-14-generic #17-Ubuntu SMP Thu Feb 6 22:47:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu Focal Fossa (development branch)
Release:	20.04
Codename:	focal
# docker info
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 33
 Server Version: 19.03.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version:
 runc version:
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-14-generic
 Operating System: Ubuntu Focal Fossa (development branch)
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 1.941GiB
 Name: pivorak-production-eu
 ID: T2NY:32NS:TMLC:DK6M:LPC6:ZXZM:M4LL:K3FQ:J2BO:IZC7:LFEF:VTNW
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by cpuguy83** [comment]
@g3d Can you paste information about the issue? What does the dockerd logs say?
