### ISSUE TITLE
Docker in Docker (DinD) commit behaviour 

### ISSUE THREAD

**Issue by AndrewNeudegg** [docker/for-linux#506]
# Overview 
When using [DinD (FROM docker:dind)](https://hub.docker.com/_/docker/), if I pull an image (say alpine:latest) inside the container and then commit the DinD image on the host, when I launch the newly committed image the fresh container does not have the downloaded image inside of it. 

## Steps to reproduce 
```bash
docker run -it --privileged docker:dind sh
# Enters container
dockerd &
docker pull alpine:latest
# Wait for download to complete.
```
In a new terminal:
```bash
docker ps
# Output for illustrative example.
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                  PORTS               NAMES
f4919dc087e9        docker:dind       "/bin/sh"           2 seconds ago       Up Less than a second                       gallant_wing
# We take that container ID and commit it.
docker commit f4919dc087e9 example:latest
# This image will now be stored.
```
Exit the container and start the newly committed image.
```
docker run -it --privileged example:latest sh
dockerd & 
docker images
REPOSITORY                                                                                               TAG                 IMAGE ID            CREATED             SIZE
```
## Expected behavior
If these steps are reproduced with a `touch HelloWorld.txt`, that file will be present on starting the new container. I would like to see this behavior for the downloaded images. 

## System
**Output of `docker version`:**
```
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:49:01 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 9
 Running: 0
 Paused: 0
 Stopped: 9
Images: 40
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: c4446665cb9c30056f4998ed953e6d4ff22c7c39
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-39-generic
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.6GiB
Name: andrew-mobilepc
ID: EOVK:OHCR:HT5Z:VLVI:3KTS:ORA4:4T2O:Y2DY:LUGR:2QVK:NWP6:GCJN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

## Additional notes
I have tried;

- Mounting the docker socket (does not produce the effect I want).
- Mounting the `/var/lib/docker/` directory.
- Using the `ADD` command on the `/var/lib/docker/`.
- Using the `COPY` command on the `/var/lib/docker/` directory.

These last two points induce an odd error:
```info
> sudo docker build -f test.dockerfile -t test01:1 /var/lib/docker
double free or corruption (out)
SIGABRT: abort
PC=0x7fd94d66ae97 m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4afd50, 0xc420051cc0, 0xc420051ce8)
	/usr/lib/go-1.8/src/runtime/cgocall.go:131 +0xe2 fp=0xc420051c90 sp=0xc420051c50
github.com/docker/docker-credential-helpers/secretservice._Cfunc_free(0x14ad920)
	github.com/docker/docker-credential-helpers/secretservice/_obj/_cgo_gotypes.go:111 +0x41 fp=0xc420051cc0 sp=0xc420051c90
github.com/docker/docker-credential-helpers/secretservice.Secretservice.List.func5(0x14ad920)
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linu0
github.com/docker/docker-credential-helpers/secretservice.Secretservice.List(0x0, 0x756060, 0xc420014390)
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linu8
github.com/docker/docker-credential-helpers/secretservice.(*Secretservice).List(0x77e548, 0xc420051e88, 0x410022, 0xc4200142f0)
	<autogenerated>:4 +0x46 fp=0xc420051de0 sp=0xc420051da0
github.com/docker/docker-credential-helpers/credentials.List(0x756ba0, 0x77e548, 0x7560e0, 0xc42000e018, 0x0, 0x10)
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linu0
github.com/docker/docker-credential-helpers/credentials.HandleCommand(0x756ba0, 0x77e548, 0x7ffcc665984d, 0x4, 0x7560a0, 0xc42000e010, 0x)
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linu8
github.com/docker/docker-credential-helpers/credentials.Serve(0x756ba0, 0x77e548)
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linu8
main.main()
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/secretservice/c8
runtime.main()
	/usr/lib/go-1.8/src/runtime/proc.go:185 +0x20a fp=0xc420051fe0 sp=0xc420051f88
runtime.goexit()
	/usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420051fe8 sp=0xc420051fe0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1

rax    0x0
rbx    0x7ffcc66576a0
rcx    0x7fd94d66ae97
rdx    0x0
rdi    0x2
rsi    0x7ffcc6657430
rbp    0x7ffcc66577a0
rsp    0x7ffcc6657430
r8     0x0
r9     0x7ffcc6657430
r10    0x8
r11    0x246
r12    0x7ffcc66576a0
r13    0x1000
r14    0x0
r15    0x30
rip    0x7fd94d66ae97
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
ERRO[0048] Can't add file /var/lib/docker/overlay2/01086ab4e9fb6895fad38f03e130be67ec7b2850e6f2765130fa479adb389f84/diff/run/docker/conta 
ERRO[0048] Can't add file /var/lib/docker/overlay2/01086ab4e9fb6895fad38f03e130be67ec7b2850e6f2765130fa479adb389f84/diff/run/docker.sock  
ERRO[0054] Can't add file /var/lib/docker/overlay2/1b25421e57918294d99475a31f13ed51dbce1b62aab836fa0a9422b95c6633d9/diff/run/docker/conta 
ERRO[0054] Can't add file /var/lib/docker/overlay2/1b25421e57918294d99475a31f13ed51dbce1b62aab836fa0a9422b95c6633d9/diff/run/docker/conta 
ERRO[0054] Can't add file /var/lib/docker/overlay2/1b25421e57918294d99475a31f13ed51dbce1b62aab836fa0a9422b95c6633d9/diff/run/docker/libne 
ERRO[0054] Can't add file /var/lib/docker/overlay2/1b25421e57918294d99475a31f13ed51dbce1b62aab836fa0a9422b95c6633d9/diff/run/docker/metri 
ERRO[0054] Can't add file /var/lib/docker/overlay2/1b25421e57918294d99475a31f13ed51dbce1b62aab836fa0a9422b95c6633d9/diff/run/docker.sock  
^Cnding build context to Docker daemon  1.862GB
```
The contents of this docker file are:
```dockerfile
FROM docker:dind

COPY ./image/overlay2/ /var/lib/docker/image/overlay2/
COPY ./containerd/ /var/lib/docker/containerd/
COPY ./builder/ /var/lib/docker/builder/
COPY ./trust/ /var/lib/docker/trust/
COPY ./plugins/ /var/lib/docker/plugins/
```
The later errors are ok, I don't wish to include an active socket.. nor does it make sense, however, the former error seems to be interesting.

I don't really know what to make of this and would appreciate any help.

Thanks,

Andrew

**Comment by cpuguy83** [comment]
DinD means running a new instance of dockerd inside of a container.
You cannot share state between dockerd instances.

What are you trying to accomplish with this?

**Comment by tommyknows** [comment]
Hi, 
I'd actually like to do the exact same - run dind, build a container inside of it and commit the whole Dind container. 
Did you found a solution to your issue?

**Comment by elhigu** [comment]
I'm also trying to do the same. I commit docker:dind container which has already some pre pulled images inside to local/dind-with-images and then try to run that container in CI so I don't have to pull them again and again on every run. Basically usecase is to commit dind container to be able to cache images that have already been pulled (docker save / docker load is so slow that I would prefer this method).

Here is tests reproduction code showing how it doesn't work as expected:

```
mlepisto@jen:~/test-dind-commit$ docker run --detach --rm --privileged --name root-dind docker:dind
32494881bdb4e9e2a395897701977d82403fe03960088a3dd1ee3509b9f7ed78
mlepisto@jen:~/test-dind-commit$ docker exec root-dind docker pull alpine
Using default tag: latest
latest: Pulling from library/alpine
e7c96db7181b: Pulling fs layer
e7c96db7181b: Verifying Checksum
e7c96db7181b: Download complete
e7c96db7181b: Pull complete
Digest: sha256:769fddc7cc2f0a1c35abb2f91432e8beecf83916c421420e6a6da9f8975464b6
Status: Downloaded newer image for alpine:latest

mlepisto@jen:~/test-dind-commit$ docker exec root-dind docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
alpine              latest              055936d39205        10 days ago         5.53MB

mlepisto@jen:~/test-dind-commit$ docker commit root-dind prepulled-dind
sha256:06a3836416af06cfac897d85e9dfc843691f342fc00f644f27ef2c64f77d6239

mlepisto@jen:~/test-dind-commit$ docker run --detach --rm --privileged --name prepulled-dind prepulled-dind
dcfa48c51807969eef96e874032512320031cd786047a20f90ae6033ad9ba4c7
mlepisto@jen:~/test-dind-commit$ docker exec prepulled-dind docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
mlepisto@jen:~/test-dind-commit$ docker exec prepulled-dind ls -la /var/lib/docker
total 60
drwx--x--x   15 root     root          4096 May 21 07:15 .
drwxr-xr-x    1 root     root          4096 May 21 07:13 ..
drwx------    2 root     root          4096 May 21 07:15 builder
drwx------    4 root     root          4096 May 21 07:15 buildkit
drwx------    3 root     root          4096 May 21 07:14 containerd
drwx------    2 root     root          4096 May 21 07:14 containers
drwx------    3 root     root          4096 May 21 07:14 image
drwxr-x---    3 root     root          4096 May 21 07:14 network
drwx------    3 root     root          4096 May 21 07:15 overlay2
drwx------    4 root     root          4096 May 21 07:14 plugins
drwx------    2 root     root          4096 May 21 07:14 runtimes
drwx------    2 root     root          4096 May 21 07:15 swarm
drwx------    2 root     root          4096 May 21 07:14 tmp
drwx------    2 root     root          4096 May 21 07:14 trust
drwx------    2 root     root          4096 May 21 07:14 volumes
mlepisto@jen:~/test-dind-commit$

```

So from example one can see that committed image actually does have stuff populated in /var/lib/docker , but images are still not showing. 

With some more testing I was able to figure out that the problem is that `/var/lib/docker/overlay2` directory is not committed completely when `docker commit root-dind prepulled-dind`  is ran. 

Is there any workaround for that?

**Comment by elhigu** [comment]
This all is probably related to this https://github.com/moby/moby/issues/6999

**Comment by elhigu** [comment]
I was able to resolve this by creating custom docker:dind image, which sets dockerd --data-root to be in `/var-lib-docker` which is loopback device with ext4 filesystem. 

After setting that correctly I can do `docker commit custom-dind dind-with-images` and then create new containers from `dind-with-images`.

Here is the Dockerfile + entrypoint script for dind that is not using external volumes https://github.com/elhigu/gitlab-ci-dind-with-image-cache/tree/master/.gitlab-custom-dind

**Comment by cruizba** [comment]
@elhigu You made my day :)

**Comment by Macmee** [comment]
> Let me close this ticket, because this is not a bug, but the expected behavior (because the `docker:dind` image uses a volume for the data; the reason for that is;
> 
>     * _performance_ (writing data to a layered filesystem has a performance impact)
> 
>     * _state_ (containers should be stateless, and any data that should be persisted should generally be stored outside of the container's filesystem, using volumes)
> 
>     * _compatibility_; layered filesystems, such as `overlayfs` cannot run on top of the container's layered filesystem; using a volume for the data allows running the dind daemon to use `overlayfs` (otherwise `vfs` would be used, which is mostly suitable for debugging purposes only.

Volumes to solve this problem sound good to me, but it doesn't seem to work either. The official dind documentation even suggests volume mounting over /var/lib/docker too, but it doesn't seem to work at least with overlay2:

https://hub.docker.com/_/docker

`docker run --privileged --name some-docker -v /my/own/var-lib-docker:/var/lib/docker -d docker:dind`

doing an image pull here doesn't work `docker exec containername docker image pull php`

produces:

`failed to register layer: chown /var/lib/docker/overlay2/dc8fa6d82b881158ff516c0f2eeb41afd984d37cd0808fd0cc99518919fe4d17/work/work: permission denied`

and using a proper volume instead such as `-v source=dind1storage,target=/var/lib/docker` does work for the purposes of `docker image pull php` however if you stop that container and then remount the volume then you'll see nothing actually got written to it-- `docker exec newcontainer docker images` wont return the image.
