### ISSUE TITLE
Failed install on Ubuntu bionic 18.04 in WSL

### ISSUE THREAD

**Issue by tvogel8570** [docker/for-linux#852]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
After following directions on [https://docs.docker.com/install/linux/docker-ce/ubuntu/](url), docker command `sudo docker run hello-world`  should print message.

### Actual behavior

```
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.
```
attempted to start dockerd manually and received panic.  Full output is at bottom of this issue for both `sudo dockerd` and `sudo dockerd &` 

### Steps to reproduce the behavior
1. Enable WSL on Windows 10 and install Ubuntu
2. Update the installed Ubuntu with `sudo apt update && sudo apt upgrade` 
3. Follow instructions at  [https://docs.docker.com/install/linux/docker-ce/ubuntu/](url) choosing recommended approach of install from repository and latest version of docker

**Output of `docker version`:**

```
Docker version 19.03.4, build 9013bf583a
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
ERROR: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.40/info: dial unix /var/run/docker.sock: connect: permission denied
errors pretty printing info
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
WSL on Windows 10 Pro; Version 1903; build 18362.476

**Output from trying to manually start sudo dockerd**

```
sudo dockerd
INFO[2019-11-13T13:12:53.128783300-05:00] Starting up
INFO[2019-11-13T13:12:53.144911000-05:00] libcontainerd: started new containerd process  pid=2685
INFO[2019-11-13T13:12:53.145100900-05:00] parsed scheme: "unix"                         module=grpc
INFO[2019-11-13T13:12:53.145230100-05:00] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2019-11-13T13:12:53.145361700-05:00] ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}] <nil>}  module=grpc
INFO[2019-11-13T13:12:53.145508400-05:00] ClientConn switching balancer to "pick_first"  module=grpc
INFO[2019-11-13T13:12:53.188775000-05:00] starting containerd                           revision=b34a5c8af56e510852c35414db4c1f4fa6172339 version=1.2.10
INFO[2019-11-13T13:12:53.190419500-05:00] loading plugin "io.containerd.content.v1.content"...  type=io.containerd.content.v1
INFO[2019-11-13T13:12:53.190586100-05:00] loading plugin "io.containerd.snapshotter.v1.btrfs"...  type=io.containerd.snapshotter.v1
WARN[2019-11-13T13:12:53.190843200-05:00] failed to load plugin io.containerd.snapshotter.v1.btrfs  error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter"
INFO[2019-11-13T13:12:53.191001500-05:00] loading plugin "io.containerd.snapshotter.v1.aufs"...  type=io.containerd.snapshotter.v1
WARN[2019-11-13T13:12:53.203764900-05:00] failed to load plugin io.containerd.snapshotter.v1.aufs  error="modprobe aufs failed: "modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-18362-Microsoft/modules.dep.bin'\nmodprobe: FATAL: Module aufs not found in directory /lib/modules/4.4.0-18362-Microsoft\n": exit status 1"
INFO[2019-11-13T13:12:53.203969000-05:00] loading plugin "io.containerd.snapshotter.v1.native"...  type=io.containerd.snapshotter.v1
INFO[2019-11-13T13:12:53.204137500-05:00] loading plugin "io.containerd.snapshotter.v1.overlayfs"...  type=io.containerd.snapshotter.v1
INFO[2019-11-13T13:12:53.205538400-05:00] loading plugin "io.containerd.snapshotter.v1.zfs"...  type=io.containerd.snapshotter.v1
INFO[2019-11-13T13:12:53.205809900-05:00] skip loading plugin "io.containerd.snapshotter.v1.zfs"...  type=io.containerd.snapshotter.v1
INFO[2019-11-13T13:12:53.205986600-05:00] loading plugin "io.containerd.metadata.v1.bolt"...  type=io.containerd.metadata.v1
WARN[2019-11-13T13:12:53.206131900-05:00] could not use snapshotter btrfs in metadata plugin  error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter"
WARN[2019-11-13T13:12:53.206300800-05:00] could not use snapshotter aufs in metadata plugin  error="modprobe aufs failed: "modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-18362-Microsoft/modules.dep.bin'\nmodprobe: FATAL: Module aufs not found in directory /lib/modules/4.4.0-18362-Microsoft\n": exit status 1"
WARN[2019-11-13T13:12:53.206487800-05:00] could not use snapshotter zfs in metadata plugin  error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter: skip plugin"
INFO[2019-11-13T13:12:53.207072600-05:00] loading plugin "io.containerd.differ.v1.walking"...  type=io.containerd.differ.v1
INFO[2019-11-13T13:12:53.207213200-05:00] loading plugin "io.containerd.gc.v1.scheduler"...  type=io.containerd.gc.v1
INFO[2019-11-13T13:12:53.207396800-05:00] loading plugin "io.containerd.service.v1.containers-service"...  type=io.containerd.service.v1
INFO[2019-11-13T13:12:53.207532000-05:00] loading plugin "io.containerd.service.v1.content-service"...  type=io.containerd.service.v1
INFO[2019-11-13T13:12:53.207662000-05:00] loading plugin "io.containerd.service.v1.diff-service"...  type=io.containerd.service.v1
INFO[2019-11-13T13:12:53.207792700-05:00] loading plugin "io.containerd.service.v1.images-service"...  type=io.containerd.service.v1
INFO[2019-11-13T13:12:53.210905600-05:00] loading plugin "io.containerd.service.v1.leases-service"...  type=io.containerd.service.v1
INFO[2019-11-13T13:12:53.211037900-05:00] loading plugin "io.containerd.service.v1.namespaces-service"...  type=io.containerd.service.v1
INFO[2019-11-13T13:12:53.211168800-05:00] loading plugin "io.containerd.service.v1.snapshots-service"...  type=io.containerd.service.v1
INFO[2019-11-13T13:12:53.211329400-05:00] loading plugin "io.containerd.runtime.v1.linux"...  type=io.containerd.runtime.v1
INFO[2019-11-13T13:12:53.212543100-05:00] loading plugin "io.containerd.runtime.v2.task"...  type=io.containerd.runtime.v2
INFO[2019-11-13T13:12:53.214017500-05:00] loading plugin "io.containerd.monitor.v1.cgroups"...  type=io.containerd.monitor.v1
INFO[2019-11-13T13:12:53.214544800-05:00] loading plugin "io.containerd.service.v1.tasks-service"...  type=io.containerd.service.v1
INFO[2019-11-13T13:12:53.214684100-05:00] loading plugin "io.containerd.internal.v1.restart"...  type=io.containerd.internal.v1
INFO[2019-11-13T13:12:53.214837200-05:00] loading plugin "io.containerd.grpc.v1.containers"...  type=io.containerd.grpc.v1
INFO[2019-11-13T13:12:53.214963100-05:00] loading plugin "io.containerd.grpc.v1.content"...  type=io.containerd.grpc.v1
INFO[2019-11-13T13:12:53.215088100-05:00] loading plugin "io.containerd.grpc.v1.diff"...  type=io.containerd.grpc.v1
INFO[2019-11-13T13:12:53.215211300-05:00] loading plugin "io.containerd.grpc.v1.events"...  type=io.containerd.grpc.v1
INFO[2019-11-13T13:12:53.215336700-05:00] loading plugin "io.containerd.grpc.v1.healthcheck"...  type=io.containerd.grpc.v1
INFO[2019-11-13T13:12:53.215516800-05:00] loading plugin "io.containerd.grpc.v1.images"...  type=io.containerd.grpc.v1
INFO[2019-11-13T13:12:53.215643700-05:00] loading plugin "io.containerd.grpc.v1.leases"...  type=io.containerd.grpc.v1
INFO[2019-11-13T13:12:53.215768400-05:00] loading plugin "io.containerd.grpc.v1.namespaces"...  type=io.containerd.grpc.v1
INFO[2019-11-13T13:12:53.215892900-05:00] loading plugin "io.containerd.internal.v1.opt"...  type=io.containerd.internal.v1
INFO[2019-11-13T13:12:53.216087200-05:00] loading plugin "io.containerd.grpc.v1.snapshots"...  type=io.containerd.grpc.v1
INFO[2019-11-13T13:12:53.216216700-05:00] loading plugin "io.containerd.grpc.v1.tasks"...  type=io.containerd.grpc.v1
INFO[2019-11-13T13:12:53.216340600-05:00] loading plugin "io.containerd.grpc.v1.version"...  type=io.containerd.grpc.v1
INFO[2019-11-13T13:12:53.216515400-05:00] loading plugin "io.containerd.grpc.v1.introspection"...  type=io.containerd.grpc.v1
INFO[2019-11-13T13:12:53.220458200-05:00] serving...                                    address="/var/run/docker/containerd/containerd-debug.sock"
INFO[2019-11-13T13:12:53.223922000-05:00] serving...                                    address="/var/run/docker/containerd/containerd.sock"
INFO[2019-11-13T13:12:53.224105400-05:00] containerd successfully booted in 0.036828s
INFO[2019-11-13T13:12:53.245578800-05:00] parsed scheme: "unix"                         module=grpc
INFO[2019-11-13T13:12:53.245957900-05:00] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2019-11-13T13:12:53.246117300-05:00] ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}] <nil>}  module=grpc
INFO[2019-11-13T13:12:53.246269800-05:00] ClientConn switching balancer to "pick_first"  module=grpc
INFO[2019-11-13T13:12:53.249032100-05:00] parsed scheme: "unix"                         module=grpc
INFO[2019-11-13T13:12:53.249159000-05:00] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2019-11-13T13:12:53.249283400-05:00] ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}] <nil>}  module=grpc
INFO[2019-11-13T13:12:53.249418100-05:00] ClientConn switching balancer to "pick_first"  module=grpc
INFO[2019-11-13T13:12:53.280559700-05:00] stopping healthcheck following graceful shutdown  module=libcontainerd
INFO[2019-11-13T13:12:53.280598500-05:00] stopping event stream following graceful shutdown  error="context canceled" module=libcontainerd namespace=plugins.moby
panic: invalid page type: 0: 4

goroutine 1 [running]:
github.com/docker/docker/vendor/go.etcd.io/bbolt.(*Cursor).search(0xc000920dd8, 0x7fd8c5e59410, 0x7, 0x7, 0x4)
        /go/src/github.com/docker/docker/vendor/go.etcd.io/bbolt/cursor.go:250 +0x356
github.com/docker/docker/vendor/go.etcd.io/bbolt.(*Cursor).seek(0xc000920dd8, 0x7fd8c5e59410, 0x7, 0x7, 0x7fd8c47c5300, 0x7fd8c0250001, 0xc000667dc0, 0xc000920df0, 0x7fd8c20a5114, 0xc000010118, ...)
        /go/src/github.com/docker/docker/vendor/go.etcd.io/bbolt/cursor.go:159 +0x80
github.com/docker/docker/vendor/go.etcd.io/bbolt.(*Bucket).Bucket(0xc00089c398, 0x7fd8c5e59410, 0x7, 0x7, 0xc000010118)
        /go/src/github.com/docker/docker/vendor/go.etcd.io/bbolt/bucket.go:105 +0xd7
github.com/docker/docker/vendor/go.etcd.io/bbolt.(*Tx).Bucket(...)
        /go/src/github.com/docker/docker/vendor/go.etcd.io/bbolt/tx.go:101
github.com/docker/docker/volume/service.listMeta(0xc00089c380, 0xc000000008, 0xc0001c34c0, 0x0)
        /go/src/github.com/docker/docker/volume/service/db.go:78 +0x6d
github.com/docker/docker/volume/service.(*VolumeStore).restore.func1(0xc00089c380, 0x7fd8c4a31e18, 0xc00089c380)
        /go/src/github.com/docker/docker/volume/service/restore.go:21 +0x36
github.com/docker/docker/vendor/go.etcd.io/bbolt.(*DB).View(0xc000148200, 0xc000920f98, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/go.etcd.io/bbolt/db.go:725 +0x92
github.com/docker/docker/volume/service.(*VolumeStore).restore(0xc0001005a0)
        /go/src/github.com/docker/docker/volume/service/restore.go:20 +0x94
github.com/docker/docker/volume/service.NewStore(0xc0007d4360, 0xf, 0xc0005096e0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/volume/service/store.go:107 +0xf6
github.com/docker/docker/volume/service.NewVolumeService(0xc0007d4360, 0xf, 0x7fd8c4acde60, 0xc0007772c0, 0x0, 0x0, 0x0, 0x0, 0x7fd8c4a72680, 0xc0008c61e0, ...)
        /go/src/github.com/docker/docker/volume/service/service.go:45 +0x160
github.com/docker/docker/daemon.NewDaemon(0x7fd8c4acd960, 0xc000856c80, 0xc000794500, 0xc0007772c0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/daemon.go:958 +0x1ed9
main.(*DaemonCli).start(0xc0008443f0, 0xc00005afc0, 0x0, 0x0)
        /go/src/github.com/docker/docker/cmd/dockerd/daemon.go:199 +0x7d3
main.runDaemon(...)
        /go/src/github.com/docker/docker/cmd/dockerd/docker_unix.go:13
main.newDaemonCommand.func1(0xc00017cc80, 0x7fd8c5ed4530, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/cmd/dockerd/docker.go:34 +0x7d
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).execute(0xc00017cc80, 0xc0000c8190, 0x0, 0x0, 0xc00017cc80, 0xc0000c8190)
        /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:762 +0x467
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00017cc80, 0x0, 0x0, 0x7)
        /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:852 +0x2ee
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:800
main.main()
        /go/src/github.com/docker/docker/cmd/dockerd/docker.go:97 +0x191
```

**Output from trying to manually start sudo dockerd &**

```
sudo dockerd &
[1] 2710
INFO[2019-11-13T13:13:49.473844200-05:00] Starting up
INFO[2019-11-13T13:13:49.488944400-05:00] libcontainerd: started new containerd process  pid=2727
INFO[2019-11-13T13:13:49.489159800-05:00] parsed scheme: "unix"                         module=grpc
INFO[2019-11-13T13:13:49.489281500-05:00] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2019-11-13T13:13:49.489427300-05:00] ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}] <nil>}  module=grpc
INFO[2019-11-13T13:13:49.489566600-05:00] ClientConn switching balancer to "pick_first"  module=grpc
INFO[2019-11-13T13:13:49.533372700-05:00] starting containerd                           revision=b34a5c8af56e510852c35414db4c1f4fa6172339 version=1.2.10
INFO[2019-11-13T13:13:49.535054300-05:00] loading plugin "io.containerd.content.v1.content"...  type=io.containerd.content.v1
INFO[2019-11-13T13:13:49.535213900-05:00] loading plugin "io.containerd.snapshotter.v1.btrfs"...  type=io.containerd.snapshotter.v1
WARN[2019-11-13T13:13:49.535499700-05:00] failed to load plugin io.containerd.snapshotter.v1.btrfs  error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter"
INFO[2019-11-13T13:13:49.535657500-05:00] loading plugin "io.containerd.snapshotter.v1.aufs"...  type=io.containerd.snapshotter.v1
WARN[2019-11-13T13:13:49.548108700-05:00] failed to load plugin io.containerd.snapshotter.v1.aufs  error="modprobe aufs failed: "modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-18362-Microsoft/modules.dep.bin'\nmodprobe: FATAL: Module aufs not found in directory /lib/modules/4.4.0-18362-Microsoft\n": exit status 1"
INFO[2019-11-13T13:13:49.548321700-05:00] loading plugin "io.containerd.snapshotter.v1.native"...  type=io.containerd.snapshotter.v1
INFO[2019-11-13T13:13:49.548482300-05:00] loading plugin "io.containerd.snapshotter.v1.overlayfs"...  type=io.containerd.snapshotter.v1
INFO[2019-11-13T13:13:49.549969400-05:00] loading plugin "io.containerd.snapshotter.v1.zfs"...  type=io.containerd.snapshotter.v1
INFO[2019-11-13T13:13:49.550221300-05:00] skip loading plugin "io.containerd.snapshotter.v1.zfs"...  type=io.containerd.snapshotter.v1
INFO[2019-11-13T13:13:49.550348400-05:00] loading plugin "io.containerd.metadata.v1.bolt"...  type=io.containerd.metadata.v1
WARN[2019-11-13T13:13:49.550498900-05:00] could not use snapshotter btrfs in metadata plugin  error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter"
WARN[2019-11-13T13:13:49.550747200-05:00] could not use snapshotter aufs in metadata plugin  error="modprobe aufs failed: "modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-18362-Microsoft/modules.dep.bin'\nmodprobe: FATAL: Module aufs not found in directory /lib/modules/4.4.0-18362-Microsoft\n": exit status 1"
WARN[2019-11-13T13:13:49.550928000-05:00] could not use snapshotter zfs in metadata plugin  error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter: skip plugin"
INFO[2019-11-13T13:13:49.551530500-05:00] loading plugin "io.containerd.differ.v1.walking"...  type=io.containerd.differ.v1
INFO[2019-11-13T13:13:49.551695300-05:00] loading plugin "io.containerd.gc.v1.scheduler"...  type=io.containerd.gc.v1
INFO[2019-11-13T13:13:49.551863800-05:00] loading plugin "io.containerd.service.v1.containers-service"...  type=io.containerd.service.v1
INFO[2019-11-13T13:13:49.551999800-05:00] loading plugin "io.containerd.service.v1.content-service"...  type=io.containerd.service.v1
INFO[2019-11-13T13:13:49.552128700-05:00] loading plugin "io.containerd.service.v1.diff-service"...  type=io.containerd.service.v1
INFO[2019-11-13T13:13:49.555075800-05:00] loading plugin "io.containerd.service.v1.images-service"...  type=io.containerd.service.v1
INFO[2019-11-13T13:13:49.555225000-05:00] loading plugin "io.containerd.service.v1.leases-service"...  type=io.containerd.service.v1
INFO[2019-11-13T13:13:49.555355600-05:00] loading plugin "io.containerd.service.v1.namespaces-service"...  type=io.containerd.service.v1
INFO[2019-11-13T13:13:49.555485300-05:00] loading plugin "io.containerd.service.v1.snapshots-service"...  type=io.containerd.service.v1
INFO[2019-11-13T13:13:49.555615200-05:00] loading plugin "io.containerd.runtime.v1.linux"...  type=io.containerd.runtime.v1
INFO[2019-11-13T13:13:49.556897000-05:00] loading plugin "io.containerd.runtime.v2.task"...  type=io.containerd.runtime.v2
INFO[2019-11-13T13:13:49.558330300-05:00] loading plugin "io.containerd.monitor.v1.cgroups"...  type=io.containerd.monitor.v1
INFO[2019-11-13T13:13:49.558872800-05:00] loading plugin "io.containerd.service.v1.tasks-service"...  type=io.containerd.service.v1
INFO[2019-11-13T13:13:49.559052900-05:00] loading plugin "io.containerd.internal.v1.restart"...  type=io.containerd.internal.v1
INFO[2019-11-13T13:13:49.559239100-05:00] loading plugin "io.containerd.grpc.v1.containers"...  type=io.containerd.grpc.v1
INFO[2019-11-13T13:13:49.559365300-05:00] loading plugin "io.containerd.grpc.v1.content"...  type=io.containerd.grpc.v1
INFO[2019-11-13T13:13:49.559490700-05:00] loading plugin "io.containerd.grpc.v1.diff"...  type=io.containerd.grpc.v1
INFO[2019-11-13T13:13:49.559680700-05:00] loading plugin "io.containerd.grpc.v1.events"...  type=io.containerd.grpc.v1
INFO[2019-11-13T13:13:49.560431000-05:00] loading plugin "io.containerd.grpc.v1.healthcheck"...  type=io.containerd.grpc.v1
INFO[2019-11-13T13:13:49.563262600-05:00] loading plugin "io.containerd.grpc.v1.images"...  type=io.containerd.grpc.v1
INFO[2019-11-13T13:13:49.569856200-05:00] loading plugin "io.containerd.grpc.v1.leases"...  type=io.containerd.grpc.v1
INFO[2019-11-13T13:13:49.575621500-05:00] loading plugin "io.containerd.grpc.v1.namespaces"...  type=io.containerd.grpc.v1
INFO[2019-11-13T13:13:49.576216600-05:00] loading plugin "io.containerd.internal.v1.opt"...  type=io.containerd.internal.v1
INFO[2019-11-13T13:13:49.576888900-05:00] loading plugin "io.containerd.grpc.v1.snapshots"...  type=io.containerd.grpc.v1
INFO[2019-11-13T13:13:49.577393200-05:00] loading plugin "io.containerd.grpc.v1.tasks"...  type=io.containerd.grpc.v1
INFO[2019-11-13T13:13:49.581590800-05:00] loading plugin "io.containerd.grpc.v1.version"...  type=io.containerd.grpc.v1
INFO[2019-11-13T13:13:49.583750900-05:00] loading plugin "io.containerd.grpc.v1.introspection"...  type=io.containerd.grpc.v1
INFO[2019-11-13T13:13:49.588760400-05:00] serving...                                    address="/var/run/docker/containerd/containerd-debug.sock"
INFO[2019-11-13T13:13:49.590884400-05:00] serving...                                    address="/var/run/docker/containerd/containerd.sock"
INFO[2019-11-13T13:13:49.593339300-05:00] containerd successfully booted in 0.061408s
INFO[2019-11-13T13:13:49.613834800-05:00] parsed scheme: "unix"                         module=grpc
INFO[2019-11-13T13:13:49.614316700-05:00] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2019-11-13T13:13:49.617345400-05:00] ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}] <nil>}  module=grpc
INFO[2019-11-13T13:13:49.617994700-05:00] ClientConn switching balancer to "pick_first"  module=grpc
INFO[2019-11-13T13:13:49.619885700-05:00] parsed scheme: "unix"                         module=grpc
INFO[2019-11-13T13:13:49.620025500-05:00] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2019-11-13T13:13:49.620617000-05:00] ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}] <nil>}  module=grpc
INFO[2019-11-13T13:13:49.621239100-05:00] ClientConn switching balancer to "pick_first"  module=grpc
INFO[2019-11-13T13:13:49.636228200-05:00] [graphdriver] using prior storage driver: overlay2
WARN[2019-11-13T13:13:49.664992800-05:00] Your kernel does not support cgroup memory limit
WARN[2019-11-13T13:13:49.665285800-05:00] Unable to find cpu cgroup in mounts
WARN[2019-11-13T13:13:49.666131900-05:00] Unable to find blkio cgroup in mounts
WARN[2019-11-13T13:13:49.666756900-05:00] Unable to find cpuset cgroup in mounts
WARN[2019-11-13T13:13:49.671329200-05:00] mountpoint for pids not found
INFO[2019-11-13T13:13:49.672112400-05:00] Loading containers: start.
WARN[2019-11-13T13:13:49.684670200-05:00] Running iptables --wait -t nat -L -n failed with message: `iptables v1.6.1: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.`, error: exit status 3
INFO[2019-11-13T13:13:49.868678400-05:00] stopping event stream following graceful shutdown  error="<nil>" module=libcontainerd namespace=moby
INFO[2019-11-13T13:13:49.869112100-05:00] stopping healthcheck following graceful shutdown  module=libcontainerd
INFO[2019-11-13T13:13:49.869120700-05:00] stopping event stream following graceful shutdown  error="context canceled" module=libcontainerd namespace=plugins.moby
failed to start daemon: Error initializing network controller: error obtaining controller instance: failed to create NAT chain DOCKER: iptables failed: iptables -t nat -N DOCKER: iptables v1.6.1: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
 (exit status 3)

[1]+  Exit 1                  sudo dockerd
```

**Comment by thaJeztah** [comment]
Is this WSL or WSL2 ? I know WSL doesn't work (as it doesn't implement all the kernel functionality needed for Docker to run) for WSL2, you can try installing Docker Desktop, which now has support for running on WSL2

**Comment by tvogel8570** [comment]
@thaJeztah thanks for getting back to me.  It was on WSL so closing this issue.
