### ISSUE TITLE
SIGSEGV after a reboot on newly installed Debian10

### ISSUE THREAD

**Issue by FrancYescO** [docker/for-linux#945]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior

docker cli commands should run normally

### Actual behavior
After a **reboot** docker-cli does not work ALL commands (also info or version) response is a SIGSEGV, `apt-get reinstall docker-ce-cli` fix the issue
```
root@frabian:/home/francyesco# docker version
unexpected fault address 0x5598baf9c2ab
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x5598baf9c2ab pc=0x5598b8f03f60]

goroutine 1 [running, locked to thread]:
runtime.throw(0x5598ba451b34, 0x5)
	/usr/local/go/src/runtime/panic.go:617 +0x74 fp=0xc00006c740 sp=0xc00006c710 pc=0x5598b8e93194
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:397 +0x405 fp=0xc00006c770 sp=0xc00006c740 pc=0x5598b8ea7f35
internal/fmtsort.init()
	<autogenerated>:1 fp=0xc00006c778 sp=0xc00006c770 pc=0x5598b8f03f60
fmt.init()
	<autogenerated>:1 +0x4c fp=0xc00006c788 sp=0xc00006c778 pc=0x5598b8f49a6c
main.init()
	<autogenerated>:1 +0x4a fp=0xc00006c798 sp=0xc00006c788 pc=0x5598ba44b08a
runtime.main()
	/usr/local/go/src/runtime/proc.go:188 +0x1d0 fp=0xc00006c7e0 sp=0xc00006c798 pc=0x5598b8e94af0
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc00006c7e8 sp=0xc00006c7e0 pc=0x5598b8ec02c1
```

### Steps to reproduce the behavior

1. install Debian 10
2. install docker as per instruction https://docs.docker.com/install/linux/docker-ce/debian/
3. reboot

**Output of `docker version`:**

```
root@frabian:/home/francyesco# docker version
Client: Docker Engine - Community
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.16
 Git commit:        369ce74a3c
 Built:             Thu Feb 13 01:27:58 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.16
  Git commit:       369ce74a3c
  Built:            Thu Feb 13 01:26:32 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
root@frabian:/home/francyesco# docker info
Client:
 Debug Mode: false

Server:
 Containers: 6
  Running: 6
  Paused: 0
  Stopped: 0
 Images: 6
 Server Version: 19.03.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-8-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 2.921GiB
 Name: frabian
 ID: 7LYO:RZ5Z:CVRD:BMC6:MITV:PY5W:QFFB:3LUN:UOAR:GQTI:KKH5:5XKC
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**physical enviroment**
```
root@frabian:/home/francyesco# cat /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 28
model name	: Intel(R) Atom(TM) CPU D510   @ 1.66GHz
stepping	: 10
microcode	: 0x107
cpu MHz		: 1662.602
cache size	: 512 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 10
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl cpuid aperfmperf pni dtes64 monitor ds_cpl tm2 ssse3 cx16 xtpr pdcm movbe lahf_lm dtherm
bugs		:
bogomips	: 3325.20
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 28
model name	: Intel(R) Atom(TM) CPU D510   @ 1.66GHz
stepping	: 10
microcode	: 0x107
cpu MHz		: 1662.602
cache size	: 512 KB
physical id	: 0
siblings	: 2
core id		: 1
cpu cores	: 2
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 10
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts nopl cpuid aperfmperf pni dtes64 monitor ds_cpl tm2 ssse3 cx16 xtpr pdcm movbe lahf_lm dtherm
bugs		:
bogomips	: 3325.20
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:
```

**Comment by thaJeztah** [comment]
Is that the full output of the panic, or were there more lines?

**Comment by FrancYescO** [comment]
Full.

Here another, this time happened without a reboot, isn't clear what caused it i was just restarting few containers (home-assistant) ... still restored it with a reinstall.

```
root@frabian:/lib/firmware# docker ps
fatal error: slice bounds out of range

runtime stack:
runtime.throw(0x55a74c3b530b, 0x19)
	/usr/local/go/src/runtime/panic.go:617 +0x74
runtime.panicslice()
	/usr/local/go/src/runtime/panic.go:51 +0x90
runtime.pcvalue(0x55a74d9b1340, 0x55a74e0d2ae0, 0x2e296666, 0x55a74ba58ba8, 0x7ffc56ea6ef8, 0x55a74cef1101, 0x55a74d9a3c60)
	/usr/local/go/src/runtime/symtab.go:652 +0x551
runtime.funcspdelta(0x55a74d9b1340, 0x55a74e0d2ae0, 0x55a74ba58ba8, 0x7ffc56ea6ef8, 0x8)
	/usr/local/go/src/runtime/symtab.go:756 +0x61
runtime.gentraceback(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc000000180, 0x0, 0x0, 0x7fffffff, 0x55a74ceae430, 0x7ffc56ea7178, 0x0, ...)
	/usr/local/go/src/runtime/traceback.go:222 +0x188c
runtime.copystack(0xc000000180, 0x20000, 0x55a74e0d2a00)
	/usr/local/go/src/runtime/stack.go:881 +0x25d
runtime.shrinkstack(0xc000000180)
	/usr/local/go/src/runtime/stack.go:1137 +0x109
runtime.scanstack(0xc000000180, 0xc00005b270)
	/usr/local/go/src/runtime/mgcmark.go:690 +0x94
runtime.newstack()
	/usr/local/go/src/runtime/stack.go:1019 +0x36b
runtime.morestack()
	/usr/local/go/src/runtime/asm_amd64.s:429 +0x84

goroutine 1 [chan receive (scan), locked to thread]:
runtime.semrelease1(0x55a74e1395f0, 0xc000201b00)
	/usr/local/go/src/runtime/sema.go:159 +0x1c6 fp=0xc0004d1b98 sp=0xc0004d1b90 pc=0x55a74ade3ef6
runtime.semrelease(...)
	/usr/local/go/src/runtime/sema.go:156
runtime.gcStart(0x1, 0x0, 0x0)
	/usr/local/go/src/runtime/mgc.go:1355 +0x334 fp=0xc0004d1c08 sp=0xc0004d1b98 pc=0x55a74adc0084
runtime.mallocgc(0x3800, 0x55a74cd28680, 0x1, 0x0)
	/usr/local/go/src/runtime/malloc.go:1032 +0x3fe fp=0xc0004d1ca8 sp=0xc0004d1c08 pc=0x55a74adb10ae
runtime.newarray(0x55a74cd28680, 0x44, 0x30)
	/usr/local/go/src/runtime/malloc.go:1085 +0x65 fp=0xc0004d1cd8 sp=0xc0004d1ca8 pc=0x55a74adb1925
runtime.makeBucketArray(0x55a74cbdae00, 0xc000439e06, 0x0, 0x55a74ada72a3, 0x55a74cb479a3)
	/usr/local/go/src/runtime/map.go:364 +0x190 fp=0xc0004d1d10 sp=0xc0004d1cd8 pc=0x55a74adb2850
runtime.hashGrow(0x55a74cbdae00, 0xc0003e16e0)
	/usr/local/go/src/runtime/map.go:1035 +0x8d fp=0xc0004d1d60 sp=0xc0004d1d10 pc=0x55a74adb45fd
runtime.mapassign_faststr(0x55a74cbdae00, 0xc0003e16e0, 0x55a74cb479a3, 0x37, 0x55a74e158360)
	/usr/local/go/src/runtime/map_faststr.go:272 +0x12a fp=0xc0004d1dc8 sp=0xc0004d1d60 pc=0x55a74adb81ea
github.com/docker/cli/vendor/github.com/modern-go/reflect2.loadGo17Types()
	/go/src/github.com/docker/cli/vendor/github.com/modern-go/reflect2/type_map.go:77 +0x355 fp=0xc0004d1e98 sp=0xc0004d1dc8 pc=0x55a74b9b2115
github.com/docker/cli/vendor/github.com/modern-go/reflect2.init.0()
	/go/src/github.com/docker/cli/vendor/github.com/modern-go/reflect2/type_map.go:28 +0x99 fp=0xc0004d1ec8 sp=0xc0004d1e98 pc=0x55a74b9b16f9
github.com/docker/cli/vendor/github.com/modern-go/reflect2.init()
	<autogenerated>:1 +0x60 fp=0xc0004d1ed8 sp=0xc0004d1ec8 pc=0x55a74b9b6910
github.com/docker/cli/vendor/github.com/json-iterator/go.init()
	<autogenerated>:1 +0x59 fp=0xc0004d1ee8 sp=0xc0004d1ed8 pc=0x55a74ba07da9
github.com/docker/cli/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json.init()
	<autogenerated>:1 +0x59 fp=0xc0004d1ef8 sp=0xc0004d1ee8 pc=0x55a74ba14a49
github.com/docker/cli/vendor/k8s.io/apimachinery/pkg/runtime/serializer.init()
	<autogenerated>:1 +0x51 fp=0xc0004d1f08 sp=0xc0004d1ef8 pc=0x55a74ba288f1
github.com/docker/cli/vendor/k8s.io/client-go/plugin/pkg/client/auth/exec.init()
	<autogenerated>:1 +0x9f fp=0xc0004d1f18 sp=0xc0004d1f08 pc=0x55a74ba32f6f
github.com/docker/cli/vendor/k8s.io/client-go/rest.init()
	<autogenerated>:1 +0x103 fp=0xc0004d1f28 sp=0xc0004d1f18 pc=0x55a74ba42423
github.com/docker/cli/vendor/k8s.io/client-go/tools/auth.init()
	<autogenerated>:1 +0x56 fp=0xc0004d1f38 sp=0xc0004d1f28 pc=0x55a74ba43516
fatal error: slice bounds out of range
panic during panic

runtime stack:
runtime.throw(0x55a74c3b530b, 0x19)
	/usr/local/go/src/runtime/panic.go:617 +0x74
runtime.panicslice()
	/usr/local/go/src/runtime/panic.go:51 +0x90
runtime.pcvalue(0x55a74d9b1340, 0x55a74e0d2ae0, 0x2e296666, 0x55a74ba58ba8, 0x7ffc56ea6778, 0x55a74c38e001, 0x1)
	/usr/local/go/src/runtime/symtab.go:652 +0x551
runtime.funcspdelta(0x55a74d9b1340, 0x55a74e0d2ae0, 0x55a74ba58ba8, 0x7ffc56ea6778, 0xf)
	/usr/local/go/src/runtime/symtab.go:756 +0x61
runtime.gentraceback(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc000000180, 0x0, 0x0, 0x64, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/runtime/traceback.go:222 +0x188c
runtime.traceback1(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc000000180, 0x0)
	/usr/local/go/src/runtime/traceback.go:746 +0xf3
runtime.traceback(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc000000180)
	/usr/local/go/src/runtime/traceback.go:700 +0x54
runtime.tracebackothers(0x55a74e1393a0)
	/usr/local/go/src/runtime/traceback.go:935 +0x293
runtime.dopanic_m(0x55a74e1393a0, 0x55a74add2194, 0x7ffc56ea6ca0, 0x1)
	/usr/local/go/src/runtime/panic.go:817 +0x2a6
runtime.fatalthrow.func1()
	/usr/local/go/src/runtime/panic.go:672 +0x61
runtime.fatalthrow()
	/usr/local/go/src/runtime/panic.go:669 +0x59
runtime.throw(0x55a74c3b530b, 0x19)
	/usr/local/go/src/runtime/panic.go:617 +0x74
runtime.panicslice()
	/usr/local/go/src/runtime/panic.go:51 +0x90
runtime.pcvalue(0x55a74d9b1340, 0x55a74e0d2ae0, 0x2e296666, 0x55a74ba58ba8, 0x7ffc56ea6ef8, 0x55a74cef1101, 0x55a74d9a3c60)
	/usr/local/go/src/runtime/symtab.go:652 +0x551
runtime.funcspdelta(0x55a74d9b1340, 0x55a74e0d2ae0, 0x55a74ba58ba8, 0x7ffc56ea6ef8, 0x8)
	/usr/local/go/src/runtime/symtab.go:756 +0x61
runtime.gentraceback(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc000000180, 0x0, 0x0, 0x7fffffff, 0x55a74ceae430, 0x7ffc56ea7178, 0x0, ...)
	/usr/local/go/src/runtime/traceback.go:222 +0x188c
runtime.copystack(0xc000000180, 0x20000, 0x55a74e0d2a00)
	/usr/local/go/src/runtime/stack.go:881 +0x25d
runtime.shrinkstack(0xc000000180)
	/usr/local/go/src/runtime/stack.go:1137 +0x109
runtime.scanstack(0xc000000180, 0xc00005b270)
	/usr/local/go/src/runtime/mgcmark.go:690 +0x94
runtime.newstack()
	/usr/local/go/src/runtime/stack.go:1019 +0x36b
runtime.morestack()
	/usr/local/go/src/runtime/asm_amd64.s:429 +0x84
root@frabian:/lib/firmware# docker ps
fatal error: slice bounds out of range

runtime stack:
runtime.throw(0x55c66cb2b30b, 0x19)
	/usr/local/go/src/runtime/panic.go:617 +0x74
runtime.panicslice()
	/usr/local/go/src/runtime/panic.go:51 +0x90
runtime.pcvalue(0x55c66e127340, 0x55c66e848ae0, 0x2e296666, 0x55c66c1ceba8, 0x7ffff7202bf8, 0x55c66e081e01, 0x55c600000008)
	/usr/local/go/src/runtime/symtab.go:652 +0x551
runtime.funcspdelta(0x55c66e127340, 0x55c66e848ae0, 0x55c66c1ceba8, 0x7ffff7202bf8, 0x7fff00000008)
	/usr/local/go/src/runtime/symtab.go:756 +0x61
runtime.gentraceback(0x55c66b542e98, 0xc000209a70, 0x0, 0xc000000180, 0x0, 0xc000209ab8, 0x20, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/runtime/traceback.go:222 +0x188c
runtime.callers.func1()
	/usr/local/go/src/runtime/traceback.go:814 +0x85
runtime.systemstack(0x55c66b5730cd)
	/usr/local/go/src/runtime/asm_amd64.s:351 +0x63
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1153

goroutine 1 [running, locked to thread]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:311 fp=0xc000209a08 sp=0xc000209a00 pc=0x55c66b5731c0
runtime.callers(0x4, 0xc000209ab8, 0x20, 0x20, 0x100)
	/usr/local/go/src/runtime/traceback.go:813 +0xbf fp=0xc000209a70 sp=0xc000209a08 pc=0x55c66b56b4df
runtime.mProf_Malloc(0xc00040a000, 0x14000)
	/usr/local/go/src/runtime/mprof.go:342 +0x78 fp=0xc000209be8 sp=0xc000209a70 pc=0x55c66b542e98
runtime.profilealloc(0x55c66e8afd40, 0xc00040a000, 0x14000)
	/usr/local/go/src/runtime/malloc.go:1095 +0x5a fp=0xc000209c08 sp=0xc000209be8 pc=0x55c66b527a4a
runtime.mallocgc(0x14000, 0x55c66d4ab340, 0x1, 0x0)
	/usr/local/go/src/runtime/malloc.go:1019 +0x45f fp=0xc000209ca8 sp=0xc000209c08 pc=0x55c66b52710f
runtime.newarray(0x55c66d4ab340, 0x12d, 0xc000407200)
	/usr/local/go/src/runtime/malloc.go:1085 +0x65 fp=0xc000209cd8 sp=0xc000209ca8 pc=0x55c66b527925
runtime.makeBucketArray(0x55c66d362b00, 0xc000209d08, 0x0, 0x55c66b51d2a3, 0x55c66d1af2f4)
	/usr/local/go/src/runtime/map.go:364 +0x190 fp=0xc000209d10 sp=0xc000209cd8 pc=0x55c66b528850
runtime.hashGrow(0x55c66d362b00, 0xc0003c7b60)
	/usr/local/go/src/runtime/map.go:1035 +0x8d fp=0xc000209d60 sp=0xc000209d10 pc=0x55c66b52a5fd
runtime.mapassign_faststr(0x55c66d362b00, 0xc0003c7b60, 0x55c66d1af2f4, 0xc, 0xc0003914b8)
	/usr/local/go/src/runtime/map_faststr.go:272 +0x12a fp=0xc000209dc8 sp=0xc000209d60 pc=0x55c66b52e1ea
github.com/docker/cli/vendor/github.com/modern-go/reflect2.loadGo17Types()
	/go/src/github.com/docker/cli/vendor/github.com/modern-go/reflect2/type_map.go:79 +0x240 fp=0xc000209e98 sp=0xc000209dc8 pc=0x55c66c128000
github.com/docker/cli/vendor/github.com/modern-go/reflect2.init.0()
	/go/src/github.com/docker/cli/vendor/github.com/modern-go/reflect2/type_map.go:28 +0x99 fp=0xc000209ec8 sp=0xc000209e98 pc=0x55c66c1276f9
github.com/docker/cli/vendor/github.com/modern-go/reflect2.init()
	<autogenerated>:1 +0x60 fp=0xc000209ed8 sp=0xc000209ec8 pc=0x55c66c12c910
github.com/docker/cli/vendor/github.com/json-iterator/go.init()
	<autogenerated>:1 +0x59 fp=0xc000209ee8 sp=0xc000209ed8 pc=0x55c66c17dda9
github.com/docker/cli/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json.init()
	<autogenerated>:1 +0x59 fp=0xc000209ef8 sp=0xc000209ee8 pc=0x55c66c18aa49
github.com/docker/cli/vendor/k8s.io/apimachinery/pkg/runtime/serializer.init()
	<autogenerated>:1 +0x51 fp=0xc000209f08 sp=0xc000209ef8 pc=0x55c66c19e8f1
github.com/docker/cli/vendor/k8s.io/client-go/plugin/pkg/client/auth/exec.init()
	<autogenerated>:1 +0x9f fp=0xc000209f18 sp=0xc000209f08 pc=0x55c66c1a8f6f
github.com/docker/cli/vendor/k8s.io/client-go/rest.init()
	<autogenerated>:1 +0x103 fp=0xc000209f28 sp=0xc000209f18 pc=0x55c66c1b8423
github.com/docker/cli/vendor/k8s.io/client-go/tools/auth.init()
	<autogenerated>:1 +0x56 fp=0xc000209f38 sp=0xc000209f28 pc=0x55c66c1b9516
fatal error: slice bounds out of range
panic during panic

runtime stack:
runtime.throw(0x55c66cb2b30b, 0x19)
	/usr/local/go/src/runtime/panic.go:617 +0x74
runtime.panicslice()
	/usr/local/go/src/runtime/panic.go:51 +0x90
runtime.pcvalue(0x55c66e127340, 0x55c66e848ae0, 0x2e296666, 0x55c66c1ceba8, 0x7ffff7202478, 0x55c66cb04001, 0x1)
	/usr/local/go/src/runtime/symtab.go:652 +0x551
runtime.funcspdelta(0x55c66e127340, 0x55c66e848ae0, 0x55c66c1ceba8, 0x7ffff7202478, 0xf)
	/usr/local/go/src/runtime/symtab.go:756 +0x61
runtime.gentraceback(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc000000180, 0x0, 0x0, 0x64, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/runtime/traceback.go:222 +0x188c
runtime.traceback1(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc000000180, 0x0)
	/usr/local/go/src/runtime/traceback.go:746 +0xf3
runtime.traceback(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc000000180)
	/usr/local/go/src/runtime/traceback.go:700 +0x54
runtime.tracebackothers(0x55c66e8af3a0)
	/usr/local/go/src/runtime/traceback.go:935 +0x293
runtime.dopanic_m(0x55c66e8af3a0, 0x55c66b548194, 0x7ffff72029a0, 0x1)
	/usr/local/go/src/runtime/panic.go:817 +0x2a6
runtime.fatalthrow.func1()
	/usr/local/go/src/runtime/panic.go:672 +0x61
runtime.fatalthrow()
	/usr/local/go/src/runtime/panic.go:669 +0x59
runtime.throw(0x55c66cb2b30b, 0x19)
	/usr/local/go/src/runtime/panic.go:617 +0x74
runtime.panicslice()
	/usr/local/go/src/runtime/panic.go:51 +0x90
runtime.pcvalue(0x55c66e127340, 0x55c66e848ae0, 0x2e296666, 0x55c66c1ceba8, 0x7ffff7202bf8, 0x55c66e081e01, 0x55c600000008)
	/usr/local/go/src/runtime/symtab.go:652 +0x551
runtime.funcspdelta(0x55c66e127340, 0x55c66e848ae0, 0x55c66c1ceba8, 0x7ffff7202bf8, 0x7fff00000008)
	/usr/local/go/src/runtime/symtab.go:756 +0x61
runtime.gentraceback(0x55c66b542e98, 0xc000209a70, 0x0, 0xc000000180, 0x0, 0xc000209ab8, 0x20, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/runtime/traceback.go:222 +0x188c
runtime.callers.func1()
	/usr/local/go/src/runtime/traceback.go:814 +0x85
runtime.systemstack(0x55c66b5730cd)
	/usr/local/go/src/runtime/asm_amd64.s:351 +0x63
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1153
```

**Comment by thaJeztah** [comment]
Thanks for that; not near my computer right now, but at a glance looks like the issue originates from the kubernetes dependency code 🤔

**Comment by thaJeztah** [comment]
Let me at least transfer this issue to the CLI issue tracker, as that's where the code lives
