### ISSUE TITLE
Failed to start Docker Application Container Engine.

### ISSUE THREAD

**Issue by dongasai** [docker/for-linux#984]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior

docker runing
### Actual behavior

Unable to start
### Steps to reproduce the behavior
systemctl status docker.service

**Output of `docker version`:**

```

Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 23:42:35 2020
 OS/Arch:           linux/amd64
 Experimental:      false
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
errors pretty printing info
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

Linux xingshu-server 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Ubuntu 18.04

```
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2020-04-23 20:04:27 CST; 4min 17s ago
     Docs: https://docs.docker.com
  Process: 3141 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=2)
 Main PID: 3141 (code=exited, status=2)

4月 23 20:04:27 xingshu-server systemd[1]: docker.service: Service hold-off time over, scheduling restart.
4月 23 20:04:27 xingshu-server systemd[1]: docker.service: Scheduled restart job, restart counter is at 3.
4月 23 20:04:27 xingshu-server systemd[1]: Stopped Docker Application Container Engine.
4月 23 20:04:27 xingshu-server systemd[1]: docker.service: Start request repeated too quickly.
4月 23 20:04:27 xingshu-server systemd[1]: docker.service: Failed with result 'exit-code'.
4月 23 20:04:27 xingshu-server systemd[1]: Failed to start Docker Application Container Engine.
root@xingshu-server:/home/xingshu# systemctl restart docker.service
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
root@xingshu-server:/home/xingshu# journalctl -xe
4月 23 20:08:57 xingshu-server dockerd[4737]: time="2020-04-23T20:08:57.926699402+08:00" level=info msg="detected 127.0.0.53 nameserver, assuming systemd-resolved, so usi
4月 23 20:08:57 xingshu-server dockerd[4737]: time="2020-04-23T20:08:57.927506797+08:00" level=info msg="parsed scheme: \"unix\"" module=grpc
4月 23 20:08:57 xingshu-server dockerd[4737]: time="2020-04-23T20:08:57.927526141+08:00" level=info msg="scheme \"unix\" not registered, fallback to default scheme" modul
4月 23 20:08:57 xingshu-server dockerd[4737]: time="2020-04-23T20:08:57.927543094+08:00" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/container
4月 23 20:08:57 xingshu-server dockerd[4737]: time="2020-04-23T20:08:57.927555793+08:00" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
4月 23 20:08:57 xingshu-server dockerd[4737]: time="2020-04-23T20:08:57.928353828+08:00" level=info msg="parsed scheme: \"unix\"" module=grpc
4月 23 20:08:57 xingshu-server dockerd[4737]: time="2020-04-23T20:08:57.928369056+08:00" level=info msg="scheme \"unix\" not registered, fallback to default scheme" modul
4月 23 20:08:57 xingshu-server dockerd[4737]: time="2020-04-23T20:08:57.928384275+08:00" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/container
4月 23 20:08:57 xingshu-server dockerd[4737]: time="2020-04-23T20:08:57.928395751+08:00" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
4月 23 20:08:58 xingshu-server dockerd[4737]: time="2020-04-23T20:08:58.436568981+08:00" level=info msg="[graphdriver] using prior storage driver: overlay2"
4月 23 20:08:58 xingshu-server dockerd[4737]: time="2020-04-23T20:08:58.595324207+08:00" level=warning msg="Your kernel does not support swap memory limit"
4月 23 20:08:58 xingshu-server dockerd[4737]: time="2020-04-23T20:08:58.595345929+08:00" level=warning msg="Your kernel does not support cgroup rt period"
4月 23 20:08:58 xingshu-server dockerd[4737]: time="2020-04-23T20:08:58.595350863+08:00" level=warning msg="Your kernel does not support cgroup rt runtime"
4月 23 20:08:58 xingshu-server dockerd[4737]: time="2020-04-23T20:08:58.595355347+08:00" level=warning msg="Your kernel does not support cgroup blkio weight"
4月 23 20:08:58 xingshu-server dockerd[4737]: time="2020-04-23T20:08:58.595359676+08:00" level=warning msg="Your kernel does not support cgroup blkio weight_device"
4月 23 20:08:58 xingshu-server dockerd[4737]: time="2020-04-23T20:08:58.595496972+08:00" level=info msg="Loading containers: start."
4月 23 20:08:58 xingshu-server dockerd[4737]: panic: page 34 already freed
4月 23 20:08:58 xingshu-server dockerd[4737]: goroutine 1 [running]:
4月 23 20:08:58 xingshu-server dockerd[4737]: github.com/docker/docker/vendor/go.etcd.io/bbolt.(*freelist).free(0xc0007d8c80, 0x7e38fd, 0x7fe044082000)
4月 23 20:08:58 xingshu-server dockerd[4737]:         /build/docker.io-vLFFiY/docker.io-19.03.8/.gopath/src/github.com/docker/docker/vendor/go.etcd.io/bbolt/freelist.go:1
4月 23 20:08:58 xingshu-server dockerd[4737]: github.com/docker/docker/vendor/go.etcd.io/bbolt.(*node).spill(0xc0001ba690, 0xc000b31380, 0x1)
4月 23 20:08:58 xingshu-server dockerd[4737]:         /build/docker.io-vLFFiY/docker.io-19.03.8/.gopath/src/github.com/docker/docker/vendor/go.etcd.io/bbolt/node.go:363 +
4月 23 20:08:58 xingshu-server dockerd[4737]: github.com/docker/docker/vendor/go.etcd.io/bbolt.(*node).spill(0xc0001ba620, 0xc000c7e7e0, 0xc000e8e410)
4月 23 20:08:58 xingshu-server dockerd[4737]:         /build/docker.io-vLFFiY/docker.io-19.03.8/.gopath/src/github.com/docker/docker/vendor/go.etcd.io/bbolt/node.go:350 +
4月 23 20:08:58 xingshu-server dockerd[4737]: github.com/docker/docker/vendor/go.etcd.io/bbolt.(*Bucket).spill(0xc0000df840, 0xc000c7e700, 0xc000e8e608)
4月 23 20:08:58 xingshu-server dockerd[4737]:         /build/docker.io-vLFFiY/docker.io-19.03.8/.gopath/src/github.com/docker/docker/vendor/go.etcd.io/bbolt/bucket.go:568
4月 23 20:08:58 xingshu-server dockerd[4737]: github.com/docker/docker/vendor/go.etcd.io/bbolt.(*Bucket).spill(0xc0007db0b8, 0x2b06eef0, 0x55c2445ad6c0)
4月 23 20:08:58 xingshu-server dockerd[4737]:         /build/docker.io-vLFFiY/docker.io-19.03.8/.gopath/src/github.com/docker/docker/vendor/go.etcd.io/bbolt/bucket.go:535
4月 23 20:08:58 xingshu-server dockerd[4737]: github.com/docker/docker/vendor/go.etcd.io/bbolt.(*Tx).Commit(0xc0007db0a0, 0x0, 0x0)
4月 23 20:08:58 xingshu-server dockerd[4737]:         /build/docker.io-vLFFiY/docker.io-19.03.8/.gopath/src/github.com/docker/docker/vendor/go.etcd.io/bbolt/tx.go:160 +0x
4月 23 20:08:58 xingshu-server dockerd[4737]: github.com/docker/docker/vendor/go.etcd.io/bbolt.(*DB).Update(0xc000c78c00, 0xc000e8e8e8, 0x0, 0x0)
4月 23 20:08:58 xingshu-server dockerd[4737]:         /build/docker.io-vLFFiY/docker.io-19.03.8/.gopath/src/github.com/docker/docker/vendor/go.etcd.io/bbolt/db.go:701 +0x
4月 23 20:08:58 xingshu-server dockerd[4737]: github.com/docker/docker/vendor/github.com/docker/libkv/store/boltdb.(*BoltDB).AtomicPut(0xc0001963c0, 0xc000094a80, 0x64, 0
4月 23 20:08:58 xingshu-server dockerd[4737]:         /build/docker.io-vLFFiY/docker.io-19.03.8/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libkv/store/
4月 23 20:08:58 xingshu-server dockerd[4737]: github.com/docker/docker/vendor/github.com/docker/libnetwork/datastore.(*datastore).PutObjectAtomic(0xc00004f180, 0x55c24345
4月 23 20:08:58 xingshu-server dockerd[4737]:         /build/docker.io-vLFFiY/docker.io-19.03.8/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/d
4月 23 20:08:58 xingshu-server dockerd[4737]: github.com/docker/docker/vendor/github.com/docker/libnetwork.(*controller).updateToStore(0xc0007e8200, 0x55c2434542a0, 0xc00
4月 23 20:08:58 xingshu-server dockerd[4737]:         /build/docker.io-vLFFiY/docker.io-19.03.8/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/s
4月 23 20:08:58 xingshu-server dockerd[4737]: github.com/docker/docker/vendor/github.com/docker/libnetwork.(*controller).NewNetwork(0xc0007e8200, 0x55c24253e7d9, 0x4, 0x5
4月 23 20:08:58 xingshu-server dockerd[4737]:         /build/docker.io-vLFFiY/docker.io-19.03.8/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/c
4月 23 20:08:58 xingshu-server dockerd[4737]: github.com/docker/docker/daemon.(*Daemon).initNetworkController(0xc00000c5a0, 0xc0007e4500, 0xc000bda600, 0x0, 0x0, 0x0, 0x0
4月 23 20:08:58 xingshu-server dockerd[4737]:         /build/docker.io-vLFFiY/docker.io-19.03.8/.gopath/src/github.com/docker/docker/daemon/daemon_unix.go:871 +0x5a2
4月 23 20:08:58 xingshu-server dockerd[4737]: github.com/docker/docker/daemon.(*Daemon).restore(0xc00000c5a0, 0xc0007cc300, 0xc000783a20)
4月 23 20:08:58 xingshu-server dockerd[4737]:         /build/docker.io-vLFFiY/docker.io-19.03.8/.gopath/src/github.com/docker/docker/daemon/daemon.go:459 +0x50b
4月 23 20:08:58 xingshu-server dockerd[4737]: github.com/docker/docker/daemon.NewDaemon(0x55c24342a220, 0xc0007cc300, 0xc0007e4500, 0xc000724ed0, 0x0, 0x0, 0x0)
4月 23 20:08:58 xingshu-server dockerd[4737]:         /build/docker.io-vLFFiY/docker.io-19.03.8/.gopath/src/github.com/docker/docker/daemon/daemon.go:1067 +0x29ce
4月 23 20:08:58 xingshu-server dockerd[4737]: main.(*DaemonCli).start(0xc0007b4780, 0xc0007bd6e0, 0x0, 0x0)
4月 23 20:08:58 xingshu-server dockerd[4737]:         /build/docker.io-vLFFiY/docker.io-19.03.8/.gopath/src/github.com/docker/docker/cmd/dockerd/daemon.go:199 +0x73e
4月 23 20:08:58 xingshu-server dockerd[4737]: main.runDaemon(...)
4月 23 20:08:58 xingshu-server dockerd[4737]:         /build/docker.io-vLFFiY/docker.io-19.03.8/.gopath/src/github.com/docker/docker/cmd/dockerd/docker_unix.go:13
4月 23 20:08:58 xingshu-server dockerd[4737]: main.newDaemonCommand.func1(0xc0007cea00, 0xc0007b4720, 0x0, 0x3, 0x0, 0x0)
4月 23 20:08:58 xingshu-server dockerd[4737]:         /build/docker.io-vLFFiY/docker.io-19.03.8/.gopath/src/github.com/docker/docker/cmd/dockerd/docker.go:34 +0x7c
4月 23 20:08:58 xingshu-server dockerd[4737]: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).execute(0xc0007cea00, 0xc0000de010, 0x3, 0x3, 0xc0007cea00
4月 23 20:08:58 xingshu-server dockerd[4737]:         /build/docker.io-vLFFiY/docker.io-19.03.8/.gopath/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command
4月 23 20:08:58 xingshu-server dockerd[4737]: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0007cea00, 0x0, 0x0, 0x10)
4月 23 20:08:58 xingshu-server dockerd[4737]:         /build/docker.io-vLFFiY/docker.io-19.03.8/.gopath/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command
4月 23 20:08:58 xingshu-server dockerd[4737]: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).Execute(...)
4月 23 20:08:58 xingshu-server dockerd[4737]:         /build/docker.io-vLFFiY/docker.io-19.03.8/.gopath/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command
4月 23 20:08:58 xingshu-server dockerd[4737]: main.main()
4月 23 20:08:58 xingshu-server dockerd[4737]:         /build/docker.io-vLFFiY/docker.io-19.03.8/.gopath/src/github.com/docker/docker/cmd/dockerd/docker.go:97 +0x191
4月 23 20:08:58 xingshu-server systemd[1]: docker.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
4月 23 20:08:58 xingshu-server systemd[1]: docker.service: Failed with result 'exit-code'.
4月 23 20:08:58 xingshu-server systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: docker.service 单元已失败
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- docker.service 单元已失败。
-- 
-- 结果为“RESULT”。

```

**Comment by dongasai** [comment]
It happened on April 20. I tried to restart it, but it didn't work

**Comment by tokkenno** [comment]
Same bug (or very similar) here. 

Occurs in a Swarm manager that had been working well for months.

**Output of `docker version`**:
```
Client: Docker Engine - Community
 Version:           19.03.9
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        9d988398e7
 Built:             Fri May 15 00:25:18 2020
 OS/Arch:           linux/amd64
 Experimental:      false
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Output of `docker info`**:
```
Client:
 Debug Mode: false

Server:
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

Linux 4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Ubuntu server 18.04

```
May 20 09:58:48 arale dockerd[2784]: panic: invalid page allocation: 0
May 20 09:58:48 arale dockerd[2784]: goroutine 1170 [running]:
May 20 09:58:48 arale dockerd[2784]: github.com/docker/docker/vendor/go.etcd.io/bbolt.(*freelist).arrayAllocate(0xc00097b200, 0xa09960, 0x1, 0x0)
May 20 09:58:48 arale dockerd[2784]:         /go/src/github.com/docker/docker/vendor/go.etcd.io/bbolt/freelist.go:117 +0x2d2
May 20 09:58:48 arale dockerd[2784]: github.com/docker/docker/vendor/go.etcd.io/bbolt.(*DB).allocate(0xc001c28000, 0xa09960, 0x1, 0x0, 0xc00120f600, 0xc000337420)
May 20 09:58:48 arale dockerd[2784]:         /go/src/github.com/docker/docker/vendor/go.etcd.io/bbolt/db.go:931 +0xa7
May 20 09:58:48 arale dockerd[2784]: github.com/docker/docker/vendor/go.etcd.io/bbolt.(*Tx).allocate(0xc0007ee8c0, 0x1, 0x7effc4014000, 0x5639701e6a40, 0x0)
May 20 09:58:48 arale dockerd[2784]:         /go/src/github.com/docker/docker/vendor/go.etcd.io/bbolt/tx.go:498 +0x4c
May 20 09:58:48 arale dockerd[2784]: github.com/docker/docker/vendor/go.etcd.io/bbolt.(*node).spill(0xc000337420, 0xc006a3b260, 0xc001978068)
May 20 09:58:48 arale dockerd[2784]:         /go/src/github.com/docker/docker/vendor/go.etcd.io/bbolt/node.go:368 +0x270
May 20 09:58:48 arale dockerd[2784]: github.com/docker/docker/vendor/go.etcd.io/bbolt.(*Bucket).spill(0xc006a13380, 0xc00185df00, 0xc001978260)
May 20 09:58:48 arale dockerd[2784]:         /go/src/github.com/docker/docker/vendor/go.etcd.io/bbolt/bucket.go:568 +0x475
May 20 09:58:48 arale dockerd[2784]: github.com/docker/docker/vendor/go.etcd.io/bbolt.(*Bucket).spill(0xc001a35300, 0xc00185df00, 0xc001978458)
May 20 09:58:48 arale dockerd[2784]:         /go/src/github.com/docker/docker/vendor/go.etcd.io/bbolt/bucket.go:535 +0x3d7
May 20 09:58:48 arale dockerd[2784]: github.com/docker/docker/vendor/go.etcd.io/bbolt.(*Bucket).spill(0xc001a352c0, 0xc00185de00, 0xc001978650)
May 20 09:58:48 arale dockerd[2784]:         /go/src/github.com/docker/docker/vendor/go.etcd.io/bbolt/bucket.go:535 +0x3d7
May 20 09:58:48 arale dockerd[2784]: github.com/docker/docker/vendor/go.etcd.io/bbolt.(*Bucket).spill(0xc0007ee8d8, 0x4c4d6eba, 0x5639701c4720)
May 20 09:58:48 arale dockerd[2784]:         /go/src/github.com/docker/docker/vendor/go.etcd.io/bbolt/bucket.go:535 +0x3d7
May 20 09:58:48 arale dockerd[2784]: github.com/docker/docker/vendor/go.etcd.io/bbolt.(*Tx).Commit(0xc0007ee8c0, 0x0, 0x0)
May 20 09:58:48 arale dockerd[2784]:         /go/src/github.com/docker/docker/vendor/go.etcd.io/bbolt/tx.go:160 +0xee
May 20 09:58:48 arale dockerd[2784]: github.com/docker/docker/vendor/go.etcd.io/bbolt.(*DB).Update(0xc001c28000, 0xc0019788c8, 0x0, 0x0)
May 20 09:58:48 arale dockerd[2784]:         /go/src/github.com/docker/docker/vendor/go.etcd.io/bbolt/db.go:701 +0x108
May 20 09:58:48 arale dockerd[2784]: github.com/docker/docker/vendor/github.com/docker/swarmkit/agent.(*worker).Init(0xc000050980, 0x56396f054240, 0xc00193e330, 0x0, 0x0)
May 20 09:58:48 arale dockerd[2784]:         /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/agent/worker.go:93 +0x118
May 20 09:58:48 arale dockerd[2784]: github.com/docker/docker/vendor/github.com/docker/swarmkit/agent.(*Agent).run(0xc000bbc000, 0x56396f054240, 0xc00193e330)
May 20 09:58:48 arale dockerd[2784]:         /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/agent/agent.go:218 +0x4e9
May 20 09:58:48 arale dockerd[2784]: created by github.com/docker/docker/vendor/github.com/docker/swarmkit/agent.(*Agent).Start.func1
May 20 09:58:48 arale dockerd[2784]:         /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/agent/agent.go:83 +0x8a
May 20 09:58:48 arale systemd[1]: docker.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 20 09:58:48 arale systemd[1]: docker.service: Failed with result 'exit-code'.
May 20 09:58:48 arale systemd[1]: Failed to start Docker Application Container Engine.
May 20 09:58:50 arale systemd[1]: docker.service: Service hold-off time over, scheduling restart.
May 20 09:58:50 arale systemd[1]: docker.service: Scheduled restart job, restart counter is at 3.
May 20 09:58:50 arale systemd[1]: Stopped Docker Application Container Engine.
May 20 09:58:50 arale systemd[1]: docker.service: Start request repeated too quickly.
May 20 09:58:50 arale systemd[1]: docker.service: Failed with result 'exit-code'.
May 20 09:58:50 arale systemd[1]: Failed to start Docker Application Container Engine.
```

I can provide full 24h logs and a copy of `/var/lib/docker/network/files/local-kv.db` if you give me a private channel.

**Comment by tokkenno** [comment]
Update: I was able to "fix" the problem removing the file .../swarm/worker/tasks.db. At least, the process starts. Some stacks failed but I guess it's to be expected. I can also provide this file if needed.

**Comment by dongasai** [comment]
I finally gave up. The operation and maintenance personnel have reinstalled docker and recovered the container step by step.The answer given by the operation and maintenance personnel is data corruption.

**Comment by Lilahamstern** [comment]
@dongasai did you check if it was because of OpenSSH/VPN it dident start.
Had the same problem, but it got solved after I disconnected from my VPN.

**Comment by Next-gerardovazquezrodriguez** [comment]
I had this error:
oct 20 17:00:59 INV03725 systemd[1]: docker.socket: Socket service docker.service not loaded, refusing.
oct 20 17:00:59 INV03725 systemd[1]: Failed to listen on Docker Socket for the API.

Uninstalled docker and removed file /etc/systemd/system/docker.service, now docker is running but images still do not run

**Comment by hyperxpizza** [comment]
Similar error here, just after installation on Ubuntu 18.04 LTS.
Followed instructions descried here: https://docs.docker.com/engine/install/ubuntu/


docker version:
```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

systemctl status docker.service
```
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2020-12-01 21:34:03 CET; 4min 10s ago
     Docs: https://docs.docker.com
  Process: 12234 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=1/FAILURE)
 Main PID: 12234 (code=exited, status=1/FAILURE)

Dec 01 21:34:01 www.kernel-panic.pl systemd[1]: Failed to start Docker Application Container Engine.
Dec 01 21:34:03 www.kernel-panic.pl systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Dec 01 21:34:03 www.kernel-panic.pl systemd[1]: docker.service: Scheduled restart job, restart counter is at 4.
Dec 01 21:34:03 www.kernel-panic.pl systemd[1]: Stopped Docker Application Container Engine.
Dec 01 21:34:04 www.kernel-panic.pl systemd[1]: docker.service: Start request repeated too quickly.
Dec 01 21:34:04 www.kernel-panic.pl systemd[1]: docker.service: Failed with result 'exit-code'.
Dec 01 21:34:04 www.kernel-panic.pl systemd[1]: Failed to start Docker Application Container Engine.
Dec 01 21:34:08 www.kernel-panic.pl systemd[1]: docker.service: Start request repeated too quickly.
Dec 01 21:34:08 www.kernel-panic.pl systemd[1]: docker.service: Failed with result 'exit-code'.
Dec 01 21:34:08 www.kernel-panic.pl systemd[1]: Failed to start Docker Application Container Engine.
```

journalctl -fu docker.service
```
-- Logs begin at Sun 2020-09-27 23:28:46 CEST. --
Dec 01 21:38:37 www.kernel-panic.pl dockerd[12367]:  (exit status 3)
Dec 01 21:38:38 www.kernel-panic.pl systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Dec 01 21:38:38 www.kernel-panic.pl systemd[1]: docker.service: Failed with result 'exit-code'.
Dec 01 21:38:38 www.kernel-panic.pl systemd[1]: Failed to start Docker Application Container Engine.
Dec 01 21:38:40 www.kernel-panic.pl systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Dec 01 21:38:40 www.kernel-panic.pl systemd[1]: docker.service: Scheduled restart job, restart counter is at 3.
Dec 01 21:38:40 www.kernel-panic.pl systemd[1]: Stopped Docker Application Container Engine.
Dec 01 21:38:40 www.kernel-panic.pl systemd[1]: docker.service: Start request repeated too quickly.
Dec 01 21:38:40 www.kernel-panic.pl systemd[1]: docker.service: Failed with result 'exit-code'.
Dec 01 21:38:40 www.kernel-panic.pl systemd[1]: Failed to start Docker Application Container Engine.
```

**Comment by polzader** [comment]
May be here the solution

https://askubuntu.com/questions/1296583/why-did-docker-get-stopped-on-unattended-upgrades

**Comment by OnkelTem** [comment]
Same here. Clean Ubuntu 20.04 on a VPS. Docker won't start. Any ideas?

**Comment by dvpsprakash** [comment]
$docker ps not worked on docker host version Debian.

I did a mistake in the /etc/docker/daemon.json file. removed end of "}" braces and added some other line.

sample output

{"crv":"P-256","d":"LxJiwrwZsQw6OXmWN6c0Q5HA2n4-SZyVERLEN8qnMO0","kid":"DQSF:I77H:LHUR:356U:3DR6:ZBIM:VYBU:TYFA:F3K6:X2QN:Y7VH:MHP6","kty":"EC","x":"OnXyZnwiikXEi7OBahJnmVq9shBRTTkvrhTT6Kn5uzg","y":"w17YYUl5_1F7FPKFTVRClHvFMKnlOtYKCcJ_oIx7D0I"}

**Comment by gopalthakur71** [comment]
I started getting this error when ubuntu 22 has been rolled out... whenever I faced this issue I changed the Ubuntu to the latest one.. and it worked for me...try doing that if possible...
